Sources/LiveViewNative/Views/Layout Containers/Scroll Views/ScrollView.swift
=> Add axes and shows-indicators to ScrollView

Sources/LiveViewNative/BuiltinRegistry.swift
=> Add EditButton

Sources/LiveViewNative/BuiltinRegistry.swift
=> Add Divider

Sources/LiveViewNative/BuiltinRegistry.swift, Sources/LiveViewNative/Views/Shapes/Shape.swift, Tests/RenderingTests/ShapeTests.swift, Tests/RenderingTests/assertMatch.swift
=> Support Circle, Ellipse, Capsule, and ContainerRelativeShape

Sources/LiveViewNative/BuiltinRegistry.swift, Sources/LiveViewNative/Views/Text Input and Output/TextEditor.swift
=> Add TextEditor

Sources/LiveViewNative/Property Wrappers/FormState.swift
Fixes a crash when focusing a local-value text field.
Previously, focusing the text field would result in two things:
1. the binding being set (which would change the mode to .local and update the localValue property)
2. the FocusState changing which would trigger a view update
But when the FormState value was read as a result of #2, the mode would be .local, the localValue property would still have the old nil value and so the force-unwrap would crash.
I'm not exactly sure why localValue wouldn't return the new value in the view update, but regardless, storing the current value and the mode together keeps them from getting out of sync.
=> Don't use State property to store FormState local value

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift, Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
=> Don't require attribute value when locating main live view div

Sources/LiveViewNative/BuiltinRegistry.swift, Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift, Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift, Sources/LiveViewNative/CustomRegistry.swift, Sources/LiveViewNative/LiveContext.swift, Sources/LiveViewNative/LiveView.swift, Sources/LiveViewNative/LiveViewNative.docc/AddCustomModifier.md, Sources/LiveViewNative/LiveViewNative.docc/FormControls.md, Sources/LiveViewNative/LiveViewNative.docc/GettingStarted.md, Sources/LiveViewNative/Utils/DOM.swift, Sources/LiveViewNative/ViewModifierBuilder.swift
And a couple pieces of code-cleanup
=> Assorted documentation updates

lib/live_view_native_swift_ui/modifiers/grid/grid_cell_anchor.ex, lib/live_view_native_swift_ui/modifiers/grid/grid_cell_columns.ex, lib/live_view_native_swift_ui/modifiers/grid/grid_cell_unsized_axes.ex, lib/live_view_native_swift_ui/modifiers/grid/grid_column_alignment.ex, lib/live_view_native_swift_ui/platform.ex, lib/live_view_native_swift_ui/types/unit_point.ex
@carson-katri Moving https://github.com/liveviewnative/live_view_native_swift_ui/pull/7 to here as part of the monorepo migration (see https://github.com/liveviewnative/liveview-client-swiftui/pull/193)
=> Add grid modifiers

Sources/LiveViewNative/BuiltinRegistry.swift, Sources/LiveViewNative/Modifiers/TintModifier.swift, Sources/LiveViewNative/Views/Drawing and Graphics/Color.swift, Sources/LiveViewNative/Views/Images/Image.swift, Sources/LiveViewNative/Views/Shapes/Shape.swift, Sources/LiveViewNative/Views/Text Input and Output/Text.swift, Tests/RenderingTests/ShapeTests.swift
Closes #204.
Color as a View can be created a few ways:
```html
<color name="system-red" />
<hstack spacing="0">
<color red={0.9} green={0} blue={0.9} color-space="srgb" />
<color red={0.9} green={0} blue={0.9} color-space="srgb-linear" />
<color red={0.9} green={0} blue={0.9} color-space="display-p3" />
</hstack>
<color name="system-blue" opacity="0.5" />
```
=> Add Color View

Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift, Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift, Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift, Sources/LiveViewNative/LiveView.swift, Sources/LiveViewNative/NavStackEntryView.swift
Closes #39 
I implemented this as a new `NavigationMode`. It can be used like so:
```swift
config.navigationMode = .tabView(tabs: [
.init(label: Label("Received", systemImage: "tray.and.arrow.down.fill"), url: URL(string: "http://localhost:4000")!),
.init(label: Label("Account", systemImage: "person.crop.circle.fill"), url: URL(string: "http://localhost:4000/new")!),
])
```
=> Add `TabView`

Sources/LiveViewNative/NavStackEntryView.swift
Matches liveviewnative/live_view_native#7
=> Rename live binding events

Sources/LiveViewNative/Registries/BuiltinRegistry.swift, Sources/LiveViewNative/Utils/ElixirDateFormats.swift, Sources/LiveViewNative/Views/Controls and Indicators/Pickers/MultiDatePicker.swift, Tests/RenderingTests/PickerTests.swift
Closes #74
Note that this element isn't a form control, since it has a collection of values, which I think is more than can reasonably be encoded as a string.
```html
<multi-date-picker value-binding="dates" start="2023-01-01" end="2023-01-31">
<text>Dates</text>
</multi-date-picker>
```
https://user-images.githubusercontent.com/7091588/223870309-7d1fad3d-219d-4c84-8ae5-66d90c82b99c.mp4
=> Add MultiDatePicker

Sources/LiveViewNative/LiveViewNative.docc/Resources/04-03-02-initializer.swift, Sources/LiveViewNative/LiveViewNative.docc/Resources/04-03-03-properties.swift, Sources/LiveViewNative/LiveViewNative.docc/Resources/04-03-04-hearts.swift, Sources/LiveViewNative/LiveViewNative.docc/Resources/04-03-05-width-reader.swift, Sources/LiveViewNative/LiveViewNative.docc/Resources/04-03-06-gestures.swift, Sources/LiveViewNative/LiveViewNative.docc/Resources/04-03-07-pushevent.swift, Sources/LiveViewNative/Property Wrappers/Attribute.swift
This is likely to be a common attribute type.
=> Conform Int to AttributeDecodable

Sources/DocumentationExtensionGenerator/DocumentationExtensionGenerator.swift, Sources/LiveViewNative/Modifiers/Grid/GridCellAnchorModifier.swift, Sources/LiveViewNative/Modifiers/Grid/GridCellColumnsModifier.swift, Sources/LiveViewNative/Modifiers/Grid/GridCellUnsizedAxesModifier.swift, Sources/LiveViewNative/Modifiers/Grid/GridColumnAlignmentModifier.swift, Sources/LiveViewNative/Views/Layout Containers/Grids/Grid.swift, Sources/LiveViewNative/Views/Layout Containers/Grids/GridRow.swift
I also extended the `DocumentationExtensionGenerator` to rename modifiers to their snake case names.
=> Document Grid and related modifiers

Sources/LiveViewNative/Views/Images/AsyncImage.swift
=> Document AsyncImage

Sources/LiveViewNative/Views/Layout Containers/Groups/DisclosureGroup.swift
=> Document DisclosureGroup

Sources/LiveViewNative/Views/Layout Containers/Groups/Group.swift
=> Document Group

Sources/LiveViewNative/Views/Layout Containers/Groups/GroupBox.swift
=> Document GroupBox

Sources/LiveViewNative/Utils/PinnedScrollableViews.swift, Sources/LiveViewNative/Views/Layout Containers/Lazy Grids/LazyHGrid.swift, Sources/LiveViewNative/Views/Layout Containers/Lazy Grids/LazyVGrid.swift
=> Document Lazy Grids

Sources/DocumentationExtensionGenerator/DocumentationExtensionGenerator.swift, Sources/LiveViewNative/Views/Controls and Indicators/Buttons/Button.swift, Sources/LiveViewNative/Views/Controls and Indicators/Indicators/Gauge.swift, Sources/LiveViewNative/Views/Controls and Indicators/Indicators/ProgressView.swift, Sources/LiveViewNative/Views/Controls and Indicators/Menus/Menu.swift, Sources/LiveViewNative/Views/Controls and Indicators/Value Inputs/Toggle.swift, Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Table.swift, Sources/LiveViewNative/Views/Layout Containers/Forms/LabeledContent.swift, Sources/LiveViewNative/Views/Layout Containers/Groups/ControlGroup.swift, Sources/LiveViewNative/Views/Layout Containers/Groups/DisclosureGroup.swift, Sources/LiveViewNative/Views/Layout Containers/Groups/GroupBox.swift, Sources/LiveViewNative/Views/Text Input and Output/Label.swift
Closes #350 
I also adjusted the generation of `*Style` enums so their raw values can be displayed in the docs as the display name.
=> Document Label

Sources/DocumentationExtensionGenerator/DocumentationExtensionGenerator.swift, Sources/LiveViewNative/LiveViewNative.docc/TextFieldProtocol/TextFieldProtocol-disableAutocorrection.md, Sources/LiveViewNative/LiveViewNative.docc/TextFieldProtocol/TextFieldProtocol-submitLabel.md, Sources/LiveViewNative/LiveViewNative.docc/TextFieldProtocol/TextFieldProtocol-textFieldStyle.md, Sources/LiveViewNative/Views/Text Input and Output/SecureField.swift, Sources/LiveViewNative/Views/Text Input and Output/TextEditor.swift, Sources/LiveViewNative/Views/Text Input and Output/TextField.swift, Sources/LiveViewNative/Views/Text Input and Output/TextFieldProtocol.swift
=> Document TextField and SecureField

Sources/DocumentationExtensionGenerator/DocumentationExtensionGenerator.swift, Sources/LiveViewNative/LiveViewNative.docc/Controls and Indicators/RenameButton.md, Sources/LiveViewNative/Modifiers/RenameActionModifier.swift
Closes #356 
This also adds a method to append doc links to categories.
=> Document RenameButton and RenameActionModifier

Sources/LiveViewNative/Views/Layout Containers/Collection Containers/List.swift
=> Document List

Sources/LiveViewNative/Views/Layout Containers/Scroll Views/ScrollView.swift
=> Document ScrollView

Sources/DocumentationExtensionGenerator/DocumentationExtensionGenerator.swift, Sources/LiveViewNative/LiveViewNative.docc/Controls and Indicators/EditButton.md
=> Document EditButton

Sources/LiveViewNative/Modifiers/View Fundamentals Modifiers/TagModifier.swift, Sources/LiveViewNative/Views/Controls and Indicators/Buttons/Button.swift, Sources/LiveViewNative/Views/Controls and Indicators/Indicators/Gauge.swift, Sources/LiveViewNative/Views/Controls and Indicators/Indicators/ProgressView.swift, Sources/LiveViewNative/Views/Controls and Indicators/Menus/Menu.swift, Sources/LiveViewNative/Views/Controls and Indicators/Pickers/Picker.swift, Sources/LiveViewNative/Views/Controls and Indicators/Value Inputs/Toggle.swift, Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Table.swift, Sources/LiveViewNative/Views/Layout Containers/Forms/LabeledContent.swift, Sources/LiveViewNative/Views/Layout Containers/Groups/ControlGroup.swift, Sources/LiveViewNative/Views/Layout Containers/Groups/DisclosureGroup.swift, Sources/LiveViewNative/Views/Layout Containers/Groups/GroupBox.swift, Sources/LiveViewNative/Views/Text Input and Output/Label.swift, Sources/LiveViewNative/Views/Text Input and Output/TextFieldProtocol.swift, lib/live_view_native_swift_ui/modifiers/tag.ex, lib/live_view_native_swift_ui/platform.ex, util/build_docs.sh
Also:
- Add the tag modifier to the Elixir lib, and document it
- Move the style enums in the docs to be nested within their view types (though it's not working for a few of them, and I can't tell why)
- Fix the build script breaking the git worktree for the docs
=> Document Picker

Sources/LiveViewNative/Views/Controls and Indicators/Pickers/DatePicker.swift
=> Document DatePicker

Sources/LiveViewNative/Views/Controls and Indicators/Pickers/MultiDatePicker.swift
=> Document MultiDatePicker

Sources/LiveViewNative/Views/Layout Containers/Forms/Form.swift
=> Document Form

Sources/LiveViewNative/Modifiers/Animations Modifiers/AnimationModifier.swift, Sources/LiveViewNative/Modifiers/Animations Modifiers/MatchedGeometryEffectModifier.swift, Sources/LiveViewNative/Modifiers/Animations Modifiers/NamespaceContext.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, Sources/LiveViewNative/Utils/Animation.swift, Sources/LiveViewNative/Utils/UnitPoint.swift, Sources/LiveViewNative/ViewTree.swift, lib/live_view_native_swift_ui/modifiers/animation.ex, lib/live_view_native_swift_ui/modifiers/matched_geometry_effect.ex, lib/live_view_native_swift_ui/platform.ex, lib/live_view_native_swift_ui/types/animation.ex, lib/live_view_native_swift_ui/types/namespace.ex, lib/live_view_native_swift_ui/types/unit_point.ex
Closes #213 
Closes #542 
https://user-images.githubusercontent.com/13581484/229627176-e9f1aa47-627c-42d4-8bd7-a72e4f1ce9ce.mp4
```html
<NamespaceContext id="animation">
<VStack modifiers={@native |> animation(animation: :default, value: Integer.to_string(@selection))}>
<%= for item <- 1..5 do %>
<Button phx-click="select" phx-value-item={item} id={Integer.to_string(item)}>
<ZStack modifiers={@native |> frame(height: 44)}>
<%= if @selection == item do %>
<RoundedRectangle
id="selection"
corner-radius="8"
modifiers={@native |> matched_geometry_effect(id: "selection", namespace: :animation)}
fill-color="system-red"
/>
<% end %>
<Text color={if @selection == item, do: "system-white", else: "system-primary"}>Item #<%= item %></Text>
</ZStack>
</Button>
<% end %>
</VStack>
</NamespaceContext> …
```
=> Add animation and matchedGeometryEffect

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/TextSelectionModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/text_selection.ex, lib/live_view_native_swift_ui/platform.ex
Closes #216 
```html
<Text modifiers={text_selection(@native, selectable: true)}>Hello, world!</Text>
```
https://user-images.githubusercontent.com/13581484/230196616-69bf1e40-f87f-44c7-9361-a68ffabcd1cd.mp4
=> Add `text_selection` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/HueRotationModifier.swift, Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/Rotation3DEffectModifier.swift, Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/RotationEffectModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, Sources/LiveViewNative/Utils/Angle.swift, lib/live_view_native_swift_ui/modifiers/hue_rotation.ex, lib/live_view_native_swift_ui/modifiers/rotation_3d_effect.ex, lib/live_view_native_swift_ui/modifiers/rotation_effect.ex, lib/live_view_native_swift_ui/platform.ex, lib/live_view_native_swift_ui/types/angle.ex, lib/live_view_native_swift_ui/types/rotation_3d_effect_axis.ex
Closes #524
Closes #525 
Closes #535
https://user-images.githubusercontent.com/13581484/230451129-8eaa5a23-7e39-4bca-bdd2-59b604b1de22.mp4
```html
<Text modifiers={rotation_3d_effect(@native, angle: {:degrees, 45}, axis: {0, 1, 0})}>
Rotation by passing an angle in degrees
</Text>
```
=> Add `rotation_effect`, `rotation_3d_effect` and `hue_rotation` modifiers

Sources/LiveViewNative/Modifiers/Lists Modifiers/RefreshableModifier.swift, Sources/LiveViewNative/Property Wrappers/Attribute.swift, Sources/LiveViewNative/Property Wrappers/Event.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/refreshable.ex, lib/live_view_native_swift_ui/platform.ex, lib/live_view_native_swift_ui/types/event.ex
```html
<List modifiers={refreshable(@native, action: "increment")}>
...
</List>
```
https://user-images.githubusercontent.com/13581484/231221874-2b36c087-2a32-47fd-bbc8-804ac47ba311.mp4
=> Add `refreshable` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/FontModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, Sources/LiveViewNative/Utils/Font.swift, Sources/LiveViewNative/Views/Text Input and Output/Text.swift, lib/live_view_native_swift_ui/modifiers/font.ex, lib/live_view_native_swift_ui/platform.ex, lib/live_view_native_swift_ui/types/font.ex
=> Add `font` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/FontWeightModifier.swift, Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/FontWidthModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/font_width.ex, lib/live_view_native_swift_ui/platform.ex, lib/live_view_native_swift_ui/types/font_width.ex
Closes #302 
https://user-images.githubusercontent.com/13581484/230403171-d9117cd7-24f0-4867-8bed-c55cfe85d0d0.mp4
=> Add `font_width` modifier

Sources/LiveViewNative/LiveViewNative.docc/Tutorials/01 Initial List.tutorial
Add missing dash in the link `project files`.
=> Fix `project files` link

Sources/LiveViewNative/Modifiers/Lists Modifiers/ListStyleModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, Sources/LiveViewNative/Views/Layout Containers/Collection Containers/List.swift, Tests/RenderingTests/CollectionContainerTests.swift, lib/live_view_native_swift_ui/modifiers/list_style.ex, lib/live_view_native_swift_ui/platform.ex
=> Add `list_style` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/BaselineOffsetModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/baseline_offset.ex, lib/live_view_native_swift_ui/platform.ex
=> Add `baseline_offset` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/BlurModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/blur.ex, lib/live_view_native_swift_ui/platform.ex
=> Add `blur` modifier

Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/FixedSizeModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/fixed_size.ex, lib/live_view_native_swift_ui/platform.ex
=> Add `fixed_size` modifier

Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/LayoutPriorityModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/layout_priority.ex, lib/live_view_native_swift_ui/platform.ex
=> Add `layout_priority` modifier

Sources/LiveViewNative/Modifiers/PositionModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/position.ex, lib/live_view_native_swift_ui/platform.ex
=> Add `position` modifier

Sources/LiveViewNative/Modifiers/Lists Modifiers/HeaderProminenceModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, Sources/LiveViewNative/Utils/Prominence.swift, lib/live_view_native_swift_ui/modifiers/header_prominence.ex, lib/live_view_native_swift_ui/platform.ex
=> Add `header_prominence` modifier

Sources/LiveViewNative/LiveViewNative.docc/Resources/01-03-03-images.ios.heex
Use url instead of src for AsyncImage.
=> Update tutorial section 3

Sources/LiveViewNative/Modifiers/Input Events Modifiers/OnHoverModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/on_hover.ex
=> Add `on_hover` modifier

Sources/LiveViewNative/Modifiers/Navigation Modifiers/NavigationSubtitleModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/navigation_subtitle.ex
=> Add `navigation_subtitle` modifier

Sources/LiveViewNative/Modifiers/Lists Modifiers/ListItemTintModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, Sources/LiveViewNative/Utils/ListItemTint.swift, lib/live_view_native_swift_ui/modifiers/list_item_tint.ex, lib/live_view_native_swift_ui/types/list_item_tint.ex
=> Add `list_item_tint` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/FlipsForRightToLeftLayoutDirectionModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/flips_for_right_to_left_layout_direction.ex
=> Add `flips_for_right_to_left_layout_direction` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/KerningModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/kerning.ex
=> Add `kerning` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/MinimumScaleFactorModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/minimum_scale_factor.ex
=> Add `minimum_scale_factor` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/TrackingModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/tracking.ex
=> Add `tracking` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/LineLimitModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/line_limit.ex
=> Add `line_limit` modifier

Sources/LiveViewNative/LiveViewNative.docc/Resources/03-01-03-cat_live.ios.heex, Sources/LiveViewNative/LiveViewNative.docc/Resources/03-02-02-nav-title.ios.heex, Sources/LiveViewNative/LiveViewNative.docc/Resources/03-02-04-navigationlink.ios.heex
Update `AsyncImage` & `NavigationLink` tags.
- `AsyncImage` will use `url` instead of `src`
- `NavigationLink` will use `destination`
=> Update Tutorial - Navigation and detail view

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/CornerRadiusModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/corner_radius.ex
=> Add `corner_radius` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ScaledToFitModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/scaled_to_fit.ex
=> Add `scaled_to_fit` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ScaledToFillModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, lib/live_view_native_swift_ui/modifiers/scaled_to_fill.ex
=> Adds `scaled_to_fill` modifier

Sources/LiveViewNative/Modifiers/Controls and Indicators/ControlSizeModifier.swift, Sources/LiveViewNative/Registries/BuiltinRegistry.swift, Sources/LiveViewNative/Utils/ControlSize.swift, lib/live_view_native_swift_ui/modifiers/control_size.ex
=> Add control_size modifier

Sources/LiveViewNative/Modifiers/Lists Modifiers/ListRowSeparatorTintModifier.swift, lib/live_view_native_swift_ui/modifiers/list_row_separator_tint.ex
=> Add `list_row_separator_tint` modifier

Sources/LiveViewNative/Modifiers/Lists Modifiers/ListSectionSeparatorTintModifier.swift, lib/live_view_native_swift_ui/modifiers/list_section_separator_tint.ex
=> Add `list_section_separator_tint` modifier

Sources/LiveViewNative/Modifiers/Lists Modifiers/ListRowBackgroundModifier.swift, lib/live_view_native_swift_ui/modifiers/list_row_background.ex
=> Add `list_row_background` modifier

Sources/BuiltinRegistryGenerator/BuiltinRegistryGenerator.swift
Before: 49.7 seconds
After: 0.1 seconds
=> Optimize BuiltinRegistryGenerator

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ColorMultiplyModifier.swift, lib/live_view_native_swift_ui/modifiers/color_multiply.ex
=> Add `color_multiply` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ColorInvertModifier.swift, lib/live_view_native_swift_ui/modifiers/color_invert.ex
=> Add `color_invert` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ContrastModifier.swift, lib/live_view_native_swift_ui/modifiers/contrast.ex
=> Add `contrast` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/BrightnessModifier.swift, lib/live_view_native_swift_ui/modifiers/brightness.ex
=> Add `brightness` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/TextContentTypeModifier.swift, lib/live_view_native_swift_ui/modifiers/text_content_type.ex
=> Add `text_content_type` modifier

Sources/LiveViewNative/Modifiers/Navigation Modifiers/NavigationBarBackButtonHiddenModifier.swift, lib/live_view_native_swift_ui/modifiers/navigation_bar_back_button_hidden.ex
=> Add `navigation_bar_back_button_hidden` modifier

Sources/LiveViewNative/Modifiers/Navigation Modifiers/NavigationBarTitleDisplayModeModifier.swift, lib/live_view_native_swift_ui/modifiers/navigation_bar_title_display_mode.ex
=> Add `navigation_bar_title_display_mode` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/SaturationModifier.swift, lib/live_view_native_swift_ui/modifiers/saturation.ex
=> Add `saturation` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/GrayscaleModifier.swift, lib/live_view_native_swift_ui/modifiers/grayscale.ex
=> Add `grayscale` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ShadowModifier.swift, lib/live_view_native_swift_ui/modifiers/shadow.ex
=> Add `shadow` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/LuminanceToAlphaModifier.swift, lib/live_view_native_swift_ui/modifiers/luminance_to_alpha.ex
=> Add `luminance_to_alpha` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/DrawingGroupModifier.swift, lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/drawing_group.ex
=> Add `drawing_group` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/CompositingGroupModifier.swift, lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/compositing_group.ex
=> Add `compositing_group` modifier

Sources/LiveViewNative/Modifiers/Gestures Modifiers/DefersSystemGesturesModifier.swift, lib/live_view_native_swift_ui/modifiers/gestures/defers_system_gestures.ex
=> Add `defers_system_gestures` modifier

Sources/LiveViewNative/Modifiers/Lists Modifiers/MoveDisabledModifier.swift, lib/live_view_native_swift_ui/modifiers/lists/move_disabled.ex
=> Add `move_disabled` modifier

Sources/LiveViewNative/Modifiers/Lists Modifiers/DeleteDisabledModifier.swift, lib/live_view_native_swift_ui/modifiers/lists/delete_disabled.ex
=> Add `delete_disabled` modifier

Sources/LiveViewNative/Modifiers/Input Events Modifiers/HoverEffectModifier.swift, lib/live_view_native_swift_ui/modifiers/input_events/hover_effect.ex
=> Add `hover_effect` modifier

Sources/LiveViewNative/Modifiers/Scroll Views Modifiers/ScrollDisabledModifier.swift, lib/live_view_native_swift_ui/modifiers/scroll_views/scroll_disabled.ex
Closes #280 
This is synthesizing the `Decodable` conformance as we discussed doing in chat.
=> Add `scroll_disabled` modifier

Sources/LiveViewNative/Modifiers/Scroll Views Modifiers/ScrollContentBackgroundModifier.swift, lib/live_view_native_swift_ui/modifiers/scroll_views/scroll_content_background.ex
=> Add `scroll_content_background` modifier

Sources/LiveViewNative/Modifiers/Controls and Indicators/HorizontalRadioGroupLayoutModifier.swift, lib/live_view_native_swift_ui/modifiers/controls_and_indicators/horizontal_radio_group_layout.ex
=> Add horizontalRadioGroupLayout modifier

Sources/LiveViewNative/Modifiers/Controls and Indicators/DefaultWheelPickerItemHeightModifier.swift, lib/live_view_native_swift_ui/modifiers/controls_and_indicators/default_wheel_picker_item_height.ex
=> Add defaultWheelPickerItemHeight modifier

Sources/LiveViewNative/Modifiers/Controls and Indicators/ButtonBorderShapeModifier.swift, lib/live_view_native_swift_ui/modifiers/controls_and_indicators/button_border_shape.ex
=> Add buttonBorderShape modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/MaskModifier.swift, lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/mask.ex
=> Add `mask` modifier

Sources/LiveViewNative/Modifiers/Scroll Views Modifiers/ScrollIndicatorsModifier.swift, Sources/LiveViewNative/Utils/ScrollIndicatorVisibility.swift, lib/live_view_native_swift_ui/modifiers/scroll_views/scroll_indicators.ex
=> Add `scroll_indicators` modifier

Sources/LiveViewNative/Modifiers/Scroll Views Modifiers/ScrollDismissesKeyboardModifier.swift, Sources/LiveViewNative/Utils/ScrollDismissesKeyboardMode.swift, lib/live_view_native_swift_ui/modifiers/scroll_views/scroll_dismisses_keyboard.ex
=> Add `scroll_dismisses_keyboard` modifier

Sources/LiveViewNative/Modifiers/Input Events Modifiers/AllowsHitTestingModifier.swift, lib/live_view_native_swift_ui/modifiers/input_events/allows_hit_testing.ex
=> Add `allows_hit_testing` modifier

Sources/LiveViewNative/LiveViewNative.docc/LiveViewNative.md, Sources/LiveViewNative/Modifiers/Modal Presentations/AlertModifier.swift, Sources/LiveViewNative/Modifiers/Modal Presentations/ConfirmationDialogModifier.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/alert.ex, lib/live_view_native_swift_ui/modifiers/modal_presentations/confirmation_dialog.ex, lib/live_view_native_swift_ui/types/key_name.ex
=> Add confirmationDialog modifier

Sources/LiveViewNative/Modifiers/Gestures Modifiers/GestureModifier.swift, Sources/LiveViewNative/Modifiers/Input Events Modifiers/OnHoverModifier.swift, Sources/LiveViewNative/Modifiers/Lists Modifiers/RefreshableModifier.swift, Sources/LiveViewNative/Modifiers/Modal Presentations/SheetModifier.swift, Sources/LiveViewNative/Property Wrappers/Event.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/sheet.ex, lib/live_view_native_swift_ui/types/event.ex
=> Add sheet modifier

Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationDetentsModifier.swift, Sources/LiveViewNative/Utils/PresentationDetent.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/presentation_detents.ex, lib/live_view_native_swift_ui/types/presentation_detent.ex
=> Add presentationDetents modifier

Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationDragIndicatorModifier.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/presentation_drag_indicator.ex
=> Add presentationDragIndicator modifier

Sources/LiveViewNative/Modifiers/Modal Presentations/InteractiveDismissDisabledModifier.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/interactive_dismiss_disabled.ex
=> Add interactiveDismissDisabled modifier

Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationBackgroundModifier.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/presentation_background.ex
Closes #655
Merging is blocked by #868
=> Add presentationBackground modifier

Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationCornerRadiusModifier.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/presentation_corner_radius.ex
Closes #662 
Merging is blocked by #868
=> Add presentationCornerRadius modifier

Sources/LiveViewNative/Utils/ShapeStyle/AngularGradient.swift, Sources/LiveViewNative/Utils/ShapeStyle/AnyShapeStyle.swift, Sources/LiveViewNative/Utils/ShapeStyle/EllipticalGradient.swift, Sources/LiveViewNative/Utils/ShapeStyle/ImagePaint.swift
#837 was in flight when I made the JSON decoding changes so the CodingKeys needed to be changed to not specify camel case.
=> Update AnyShape to remove snake case keys

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/LabelStyleModifier.swift, Sources/LiveViewNative/Modifiers/Toolbars Modifiers/ToolbarColorSchemeModifier.swift, Sources/LiveViewNative/Modifiers/Toolbars Modifiers/ToolbarModifier.swift, Sources/LiveViewNative/Modifiers/Toolbars Modifiers/ToolbarTitleMenuModifier.swift, Sources/LiveViewNative/Property Wrappers/LiveContext.swift, Sources/LiveViewNative/Utils/UnitPoint.swift, Sources/LiveViewNative/Views/Text Input and Output/Text.swift, Tests/RenderingTests/Modifiers/DrawingAndGraphicsModifiersTests.swift, Tests/RenderingTests/Modifiers/LayoutAdjustmentsModifiersTests.swift, Tests/RenderingTests/Modifiers/LayoutFundamentalsModifiersTests.swift, Tests/RenderingTests/Modifiers/ListModifiersTests.swift, Tests/RenderingTests/Modifiers/NavigationModifiersTests.swift, Tests/RenderingTests/Modifiers/TextInputAndOutputModifiersTests.swift, Tests/RenderingTests/Modifiers/ToolbarModifiersTests.swift, Tests/RenderingTests/Modifiers/ViewStylesModifiersTests.swift, Tests/RenderingTests/assertMatch.swift, lib/live_view_native_swift_ui/modifiers/toolbar/toolbar_title_menu.ex
This adds tests for all of the modifiers I've implemented, with the exception of those that have no visual presentation or are incompatible with the test suite's rendering code.
=> Add modifier tests

Sources/LiveViewNative/Modifiers/View Groupings Modifiers/GroupBoxStyleModifier.swift, Sources/LiveViewNative/Views/Layout Containers/Groups/GroupBox.swift, lib/live_view_native_swift_ui/modifiers/view_groupings/group_box_style.ex
=> Add `group_box_style` modifier

.github/workflows/ci.yml, Sources/LiveViewNative/Modifiers/Images Modifiers/SymbolRenderingModeModifier.swift, lib/live_view_native_swift_ui/modifiers/images/symbol_rendering_mode.ex
Closes [#332](https://github.com/liveview-native/liveview-client-swiftui/issues/332)
=> Add `symbol_rendering_mode` modifier

Sources/LiveViewNative/Modifiers/Controls and Indicators Modifiers/ControlSizeModifier.swift, Sources/LiveViewNative/Modifiers/Controls and Indicators Modifiers/PickerStyleModifier.swift, Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/PaddingModifier.swift, Tests/RenderingTests/Modifiers/ControlsAndIndicatorsModifiersTests.swift, Tests/RenderingTests/Modifiers/DrawingAndGraphicsModifiersTests.swift, Tests/RenderingTests/Modifiers/LayoutAdjustmentsModifiersTests.swift
All the other modifiers I've added are functional and can't be tested with rendering tests
=> Add tests for assorted visual modifiers

Sources/LiveViewNative/Modifiers/Input Events Modifiers/OnDeleteCommandModifier.swift, lib/live_view_native_swift_ui/modifiers/input_events/on_delete_command.ex
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/5376d746-6302-4880-b1e9-c52af3c40649
=> Add `on_delete_command` modifier

Sources/LiveViewNative/Modifiers/Input Events Modifiers/OnSubmitModifier.swift, lib/live_view_native_swift_ui/modifiers/input_events/on_submit.ex, lib/live_view_native_swift_ui/types/submit_triggers.ex
=> Add `on_submit` modifier

Sources/LiveViewNative/Modifiers/Input Events Modifiers/OnSubmitModifier.swift, Sources/LiveViewNative/Modifiers/Input Events Modifiers/SubmitScopeModifier.swift, lib/live_view_native_swift_ui/modifiers/input_events/on_submit.ex, lib/live_view_native_swift_ui/modifiers/input_events/submit_scope.ex, lib/live_view_native_swift_ui/types/submit_triggers.ex
=> Add `submit_scope` modifier

.github/workflows/ci.yml, Sources/LiveViewNative/Modifiers/Input Events Modifiers/OnMoveCommandModifier.swift, lib/live_view_native_swift_ui/modifiers/input_events/on_move_command.ex
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/01ea57d1-2945-4846-864c-47dfa16c554b
=> Add `on_move_command` modifier

Sources/LiveViewNative/Modifiers/View Configuration Modifiers/UnredactedModifier.swift, lib/live_view_native_swift_ui/modifiers/view_configuration/unredacted.ex
=> Add `unredacted` modifier

Sources/LiveViewNative/Modifiers/Modal Presentations/AlertModifier.swift, Sources/LiveViewNative/Modifiers/Modal Presentations/ConfirmationDialogModifier.swift, Sources/LiveViewNative/Modifiers/Modal Presentations/FullScreenCoverModifier.swift, Sources/LiveViewNative/Modifiers/Modal Presentations/SheetModifier.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/full_screen_cover.ex
=> Add fullScreenCover modifier

.github/workflows/ci.yml
This adds a check for 30%+ coverage. We can increase this percentage as we go back and add more tests.
=> Add coverage validation

Sources/LiveViewNative/LiveViewNative.docc/LiveViewNative.md, Sources/LiveViewNative/Modifiers/Menus and Commands/ContextMenuModifier.swift, lib/live_view_native_swift_ui/modifiers/menus_and_commands/context_menu.ex
=> Add contextMenu modifier

Sources/LiveViewNative/Modifiers/Menus and Commands/MenuActionDismissBehaviorModifier.swift, lib/live_view_native_swift_ui/modifiers/menus_and_commands/menu_action_dismiss_behavior.ex
=> Add menuActionDismissBehavior modifier

Sources/LiveViewNative/Modifiers/Menus and Commands/MenuOrderModifier.swift, lib/live_view_native_swift_ui/modifiers/menus_and_commands/menu_order.ex
=> Add menuOrder modifier

Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationBackgroundInteractionModifier.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/presentation_background_interaction.ex
=> Add presentationBackgroundInteraction modifier

Sources/LiveViewNative/Modifiers/Modal Presentations/InteractiveDismissDisabledModifier.swift, Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationContentInteractionModifier.swift, Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationCornerRadiusModifier.swift, Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationDetentsModifier.swift, Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationDragIndicatorModifier.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/presentation_content_interaction.ex
=> Add presentationContentInteraction modifier

Sources/LiveViewNative/Modifiers/Menus and Commands/MenuStyleModifier.swift, Sources/LiveViewNative/Views/Controls and Indicators/Menus/Menu.swift, Tests/RenderingTests/Modifiers/MenusAndCommandsTestsModifiers.swift, lib/live_view_native_swift_ui/modifiers/menus_and_commands/menu_style.ex
=> Add menuStyle modifier

Sources/LiveViewNative/LiveViewNative.docc/Tutorials/01 Initial List.tutorial, Sources/LiveViewNative/LiveViewNative.docc/Tutorials/03 Navigation and Hero.tutorial, Sources/LiveViewNative/Modifiers/TransformEffectModifier.swift, Sources/LiveViewNative/Utils/CGAffineTransform.swift, Tests/RenderingTests/Modifiers/DrawingAndGraphicsModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/transform_effect.ex, lib/live_view_native_swift_ui/types/affine_transform.ex
=> Add `transform_effect` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/PrivacySensitiveModifier.swift, Tests/RenderingTests/Modifiers/TextInputAndOutputModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/text_input_and_output/privacy_sensitive.ex
=> Add `privacy_sensitive` modifier

Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/IgnoresSafeAreaModifier.swift, Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/ScenePaddingModifier.swift, lib/live_view_native_swift_ui/modifiers/layout_adjustments/ignores_safe_area.ex, lib/live_view_native_swift_ui/modifiers/layout_adjustments/scene_padding.ex
Closes #221
Closes #222
I don't believe either of these can be visually tested with how it's currently done.
=> Add layout adjustments modifiers

Sources/LiveViewNative/Modifiers/Tables Modifiers/TableStyleModifier.swift, Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Table.swift, Tests/RenderingTests/Modifiers/TablesModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/tables/table_style.ex
=> Add 'table_style' modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/KeyboardShortcutModifier.swift, Sources/LiveViewNative/Utils/EventModifiers.swift, Sources/LiveViewNative/Utils/KeyEquivalent.swift, Tests/RenderingTests/Modifiers/TextInputAndOutputModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/text_input_and_output/keyboard_shortcut.ex, lib/live_view_native_swift_ui/types/event_modifier.ex, lib/live_view_native_swift_ui/types/key_equivalent.ex
=> Add `keyboard_shortcut` modifier

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/UnderlineModifier.swift, Sources/LiveViewNative/Utils/Pattern.swift, Tests/RenderingTests/Modifiers/TextInputAndOutputModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/text_input_and_output/underline.ex
=> Add `underline` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ProjectionEffectModifier.swift, Sources/LiveViewNative/Modifiers/ProjectionEffectModifier.swift, Sources/LiveViewNative/Utils/ProjectionTransform.swift, Tests/LiveViewNativeTests/FragmentTests.swift, Tests/RenderingTests/Modifiers/DrawingAndGraphicsModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/border.ex, lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/projection_effect.ex, lib/live_view_native_swift_ui/types/projection_transform.ex
=> Add `projection_effect` modifier

Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/FrameModifier.swift, Tests/LiveViewNativeTests/DecodeModifiersTest.swift, Tests/RenderingTests/Modifiers/DrawingAndGraphicsModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/layout_adjustments/frame.ex
This is a refactor of the `frame` modifier to improve decoding and documentation. Flexible frame decoding is fixed, so you can create elements that fill the parent.
=> Fix frame modifier

Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationDetentsModifier.swift, lib/live_view_native_swift_ui/modifiers/modal_presentations/presentation_detents.ex
This allows the server to observe the height of a sheet.
=> Add selection argument to `presentation_detents` modifier

Sources/LiveViewNative/Modifiers/Drag and Drop Modifiers/DropDestinationModifier.swift, lib/live_view_native_swift_ui/modifiers/drag_and_drop/drop_destination.ex
=> Add `drop_destination` modifier

Sources/LiveViewNative/Modifiers/Layout Fundamentals Modifiers/OverlayModifier.swift, Tests/RenderingTests/Modifiers/LayoutFundamentalsModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/layout_fundamentals/overlay.ex
=> Add `overlay` modifier

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/SymbolVariantModifier.swift, Sources/LiveViewNative/Utils/SymboVariants.swift, Sources/LiveViewNative/Utils/SymbolVariants.swift, Tests/RenderingTests/Array+Decodable.swift, Tests/RenderingTests/Modifiers/DrawingAndGraphicsModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/images/symbol_variant.ex, lib/live_view_native_swift_ui/types/symbol_variants.ex
=> Add `symbol_variant` modifier

Sources/LiveViewNative/Modifiers/View Styles Modifiers/ContentShapeModifier.swift, Sources/LiveViewNative/Utils/ContentShapeKinds.swift, lib/live_view_native_swift_ui/modifiers/view_styles/content_shape.ex, lib/live_view_native_swift_ui/types/content_shape_kind.ex
=> Add `content_shape`modifier

Sources/LiveViewNative/LiveViewNative.docc/Shapes/ContainerRelativeShape.md, Sources/LiveViewNative/Modifiers/Shapes Modifiers/ContainerShapeModifier.swift, Sources/LiveViewNative/Utils/ShapeReference.swift, Tests/RenderingTests/Modifiers/ShapeModifiersTests.swift, lib/live_view_native_swift_ui/modifiers/shapes/container_shape.ex
=> Add `container_shape` modifier

Sources/LiveViewNative/ViewTree.swift, lib/live_view_native_swift_ui/modifiers/view_fundamentals/tag.ex
=> Apply tag modifier from attributes

Sources/LiveViewNative/Utils/Axis.swift
Needed to support Swift Charts modifier.
=> Add `Decodable` implementation for `Axis`

Sources/LiveViewNative/Fragment.swift, Tests/LiveViewNativeTests/FragmentTests.swift
Closes liveview-native/liveview-native-core#19 
Closes liveview-native/liveview-native-core#18
=> Fix deeply nested comprehensions

Sources/LiveViewNative/Coordinators/LiveConnectionError.swift, Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift, Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift, Sources/LiveViewNative/LiveView.swift, Sources/LiveViewNative/NavStackEntryView.swift
This PR improves the stability of navigation.
It also simplifies the networking code so it will be easier to integrate core.
=> Improve and simplify navigation

Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift
=> Change default `NavigationMode` to `enabled`

test/live_view_native/swiftui/rules_parser_test.exs
=> Add support for range types

Package.resolved, Package.swift, Package@swift-5.9.swift, Sources/LiveViewNative/LiveViewNative.docc/Tutorials/01 Initial List.tutorial, Sources/LiveViewNative/LiveViewNative.docc/Tutorials/YourFirstApp.tutorial
Legacy github address changed to new github address
=> Replace github url

.github/workflows/ci.yml, Sources/LiveViewNativeStylesheetMacros/ParseableExpressionMacro.swift, Tests/LiveViewNativeStylesheetMacrosTests/MacroTests.swift
Coverage dropped a bit, I lowered the threshold for now and more tests can be added for stylesheet parsing in separate PRs.
=> Update to use `self-hosted` tag for CI

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Fixes https://github.com/liveview-native/live_view_native/issues/66
Depends on https://github.com/liveview-native/live_view_native/pull/73
=> Fix initial connection param

Sources/LiveViewNative/Property Wrappers/ChangeTracked.swift, Sources/LiveViewNative/Property Wrappers/Event.swift
This uses strings for all `FormState` values, and improves synchronization when using `phx-debounce`/`phx-throttle`.
=> Stringify FormState and improve synchronization

Sources/LiveViewNative/Stylesheets/StylesheetParser.swift, Sources/LiveViewNativeStylesheet/ModifierParseError.swift, Sources/LiveViewNativeStylesheet/Parsing/External/Metadata.swift, Sources/LiveViewNativeStylesheet/Parsing/External/ParseableModifier.swift
Depends on #1191 
Also closes #1184
=> Include original source in client-side error messages

lib/live_view_native/swiftui/rules_parser/expressions.ex, lib/live_view_native/swiftui/rules_parser/modifiers.ex, lib/live_view_native/swiftui/rules_parser/post_processors.ex, test/live_view_native/swiftui/rules_parser_test.exs
Resolves #1231 
@carson-katri, please confirm that the ASTs are what you'd expect.
=> Support non-key-value lists

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
=> Connect live reload socket when initial connection fails

Sources/LiveViewNative/Coordinators/LiveConnectionError.swift, Sources/LiveViewNative/LiveView.swift, Sources/LiveViewNative/LiveViewPhase.swift, Sources/LiveViewNative/NavStackEntryView.swift, priv/xcodegen/Sources/TemplateApp/ConnectingView.swift, priv/xcodegen/Sources/TemplateApp/ContentView.swift, priv/xcodegen/Sources/TemplateApp/ErrorView.swift, priv/xcodegen/Sources/TemplateApp/ReconnectingView.swift
Closes #1253 
This makes some refinements to the template Views. This includes adding a flexible `frame` modifier to the content of a `ReconnectingView` to ensure the banner appears at the top of the screen.
=> Update template project Views

Sources/LiveViewNative/Stylesheets/ParseableTypes/Animation+ParseableModifierValue.swift, Sources/LiveViewNative/Stylesheets/ParseableTypes/AnySymbolEffect.swift, Sources/LiveViewNative/Stylesheets/ParseableTypes/ContentTransition+ParseableModifierValue.swift, Sources/LiveViewNative/_GeneratedModifiers.swift, Sources/ModifierGenerator/ModifierGenerator.swift
Closes #1279 
This includes new spring configurations, as well as extended `symbolEffect` modifier support.
=> Add support for more animation types

Sources/LiveViewNative/Property Wrappers/Attribute.swift
=> Decode attributes with no values to empty strings

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Closes #1235 
Stylesheet fetching happens concurrently with socket connection. After the socket is connected, we suspend until the stylesheet fetching completes. Multiple `Style` tags will be merged together.
=> Fetch stylesheets from URL

Sources/LiveViewNative/Views/Layout Containers/Lazy Grids/LazyHGrid.swift, guides/architecture/architecture.md, guides/architecture/modifiers.md, guides/architecture/navigation.md, guides/architecture/updates.md, mix.exs
* restored Architecture docs
* fixed syntax error in LazyHGrid example
=> Restores doc generations

Sources/LiveViewNative/Protocols/FormValue.swift, Sources/LiveViewNative/ViewModel.swift, Sources/LiveViewNative/Views/Controls and Indicators/Pickers/DatePicker.swift
=> Allow types to customize form encoding

Sources/LiveViewNative/Property Wrappers/ObservedElement.swift
Closes #1316 
Uses a `MergeMany` publisher to subscribe to all child elements. The publisher is rebuilt whenever the child IDs change.
=> Re-implement `observeChildren`

lib/live_view_native/swiftui/rules_parser/modifiers.ex, lib/live_view_native/swiftui/rules_parser/post_processors.ex, test/live_view_native/swiftui/rules_parser_test.exs
=> Remove `to_ime` functionality

Sources/LiveViewNative/ViewTree.swift
=> Split class names by whitespaces and newlines

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift, Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
=> Change `_lvn` to `_interface` and send on dead render

Sources/LiveViewNative/Protocols/ContentBuilder.swift, Sources/LiveViewNative/ViewTree.swift
The `style` modifiers are added before the `class` modifiers.
=> Apply classes from `style` attribute

lib/live_view_native/swiftui/rules_parser/post_processors.ex, test/live_view_native/swiftui/rules_parser_test.exs
=> Failing test for parser update

CHANGELOG.md, lib/live_view_native/swiftui.ex, test/live_view_native/swiftui/swiftui_test.exs
Depends on: https://github.com/liveview-native/live_view_native/pull/200
=> Support version normalizations

livebooks/swiftui-views.livemd
Fix issue https://github.com/liveview-native/liveview-client-swiftui/issues/1436
=> Replace system image attributes with kebab case to camel case.

CHANGELOG.md, Sources/LiveViewNative/ViewModel.swift
=> Query encode `+` characters in form events

livebooks/markdown/stylesheets.md
This PR adjusts two examples in the documentation.
=> Adjust examples in documentation

CHANGELOG.md, Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift, Sources/LiveViewNative/Stylesheets/Stylesheet.swift
Fixes the issue raised in #1460.
=> Turn `StylesheetCache` into a thread-safe actor

CHANGELOG.md, Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift, Sources/LiveViewNative/Live/LiveView.swift, Sources/LiveViewNative/Property Wrappers/Event.swift, Sources/LiveViewNative/Utils/DOM.swift, lib/live_view_native/swiftui/component.ex
=> Add `data-confirm` attribute support for all events

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
=> Provide descriptive error when the stylesheet cannot be found

CHANGELOG.md, Sources/LiveViewNative/Property Wrappers/FormState.swift
=> Trigger UI update when server changes a form field value

Sources/LiveViewNative/Stylesheets/ResolvableTypes/SwiftUI/ScrollTargetBehavior.swift
Closes #1541 
This changes the way `scrollTargetBehavior` is applied to avoid type-erasure, which fixes the scroll snapping.
=> Overload scrollTargetBehavior to get native velocity

Package.swift, Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift, Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift, Sources/LiveViewNative/Live/LiveErrorView.swift, Sources/LiveViewNative/Live/LiveView.swift
This will compile when 0.4.1-rc-2 is released. Opening it now for review.
=> Add reconnect strategy callback interface

Package.swift
This contains initial fixes for uploading progress handling.
=> bump core to 0.4.1-rc-3
