liveview-native/liveview-client-swiftui

Sources/PhoenixLiveViewNative/Views/PhxTextField.swift

Allow setting `isSecureTextEntry` property on the `UITextField` for `textfield` nodes:
https://developer.apple.com/documentation/uikit/uitextinputtraits/1624427-issecuretextentry

PhxTextField > Add isSecureTextEntry

---

Sources/LiveViewNative/Views/HStack.swift
Sources/LiveViewNative/Views/VStack.swift

This adds support for the `spacing` attribute on `VStack` and `HStack`. It expects a number that can be initialized with [`Double.init?(_ text: String)`](https://developer.apple.com/documentation/swift/double/init(_:)-5wmm8)

Support `spacing` on `VStack`/`HStack`

---

Package.swift
Tests/RenderingTests/TextTests.swift
Tests/RenderingTests/XCTestManifests.swift
Tests/RenderingTests/assertMatch.swift

This adds a new method for testing an expected View tree against the built output.
Here's an example of a test:
https://github.com/liveviewnative/liveview-client-swiftui/blob/2cb9ddbb7b1ff919ad969ecbc4eb0e3a419f8d08/Tests/RenderingTests/TextTests.swift#L14-L18
You provide the markup and an expected View, and it generates snapshots and compares them. If the snapshots match the test will pass, otherwise it will save the images for the developer to compare.

Snapshot Testing

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/ViewModel.swift
Sources/LiveViewNative/Views/Controls and Indicators/Value Inputs/Toggle.swift

Closes #71
Adds support for `Toggle` using `@FormState`. `Bool` now conforms to `FormValue` as well.
```html
<toggle name="is_on" toggle-style="switch">
Value: <%= @is_on %>
</toggle>
<toggle name="is_on" toggle-style="button">
Value: <%= @is_on %>
</toggle>
```
https://user-images.githubusercontent.com/13581484/212990111-4bf84c76-14a6-4342-afa1-3d4c85d859c9.mp4

Add `Toggle`

---

Sources/LiveViewNative/BuiltinRegistry.swift

Related to https://github.com/liveviewnative/live_view_native_swift_ui/pull/2
Uses `snake_case` names for modifiers instead of converting them to camel case on the backend automatically.

Use snake_case modifier keys

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/LiveViewNative.docc/Elements/AsyncImage.md
Sources/LiveViewNative/LiveViewNative.docc/Elements/HStack.md
Sources/LiveViewNative/LiveViewNative.docc/Elements/NavigationLink.md
Sources/LiveViewNative/LiveViewNative.docc/Elements/RoundedRectangle.md
Sources/LiveViewNative/LiveViewNative.docc/Elements/ScrollView.md
Sources/LiveViewNative/LiveViewNative.docc/Elements/TextField.md
Sources/LiveViewNative/LiveViewNative.docc/Elements/VStack.md
Sources/LiveViewNative/LiveViewNative.docc/Elements/ZStack.md
Sources/LiveViewNative/LiveViewNative.docc/Resources/01-03-03-images.ios.heex
Sources/LiveViewNative/LiveViewNative.docc/Resources/02-02-01-template.ios.heex
Sources/LiveViewNative/LiveViewNative.docc/Resources/02-02-02-button.ios.heex
Sources/LiveViewNative/LiveViewNative.docc/Resources/02-02-04-button-click.ios.heex
Sources/LiveViewNative/LiveViewNative.docc/Resources/03-01-03-cat_live.ios.heex
Sources/LiveViewNative/LiveViewNative.docc/Resources/03-02-02-nav-title.ios.heex
Sources/LiveViewNative/LiveViewNative.docc/Resources/03-02-04-navigationlink.ios.heex
Sources/LiveViewNative/LiveViewNative.docc/Resources/04-04-02-cat-rating.ios.heex
Sources/LiveViewNative/LiveViewNative.docc/Resources/05-01-03-attribute.ios.heex
Sources/LiveViewNative/LiveViewNative.docc/SupportedModifiers.md
Sources/LiveViewNative/LiveViewNative.docc/Tutorials/01 Initial List.tutorial
Sources/LiveViewNative/LiveViewNative.docc/Tutorials/02 Favorite Button.tutorial
Sources/LiveViewNative/LiveViewNative.docc/Tutorials/03 Navigation and Hero.tutorial
Sources/LiveViewNative/LiveViewNative.docc/Tutorials/05 Custom Modifier.tutorial
Sources/LiveViewNative/Views/Layout Containers/Stacks/HStack.swift
Sources/LiveViewNative/Views/Layout Containers/Stacks/VStack.swift
Tests/RenderingTests/LinkTests.swift
Tests/RenderingTests/ShapeTests.swift
Tests/RenderingTests/TextFieldTests.swift

Uses the following naming scheme across all Views:
`MyViewName` -> `my-view-name`
Affected views include `v-stack`, `scroll-view`, `navigation-link`, and others.

Consistent naming convention

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/LiveContext.swift
Sources/LiveViewNative/Views/Controls and Indicators/Menus/Menu.swift

Closes #67
This uses the prefixed slot syntax discussed in #142. If/when a custom engine is added, the following could be refactored to allow for a more familiar slot-like syntax (without any changes to the client code):
```html
<menu>
<menu:label>Change Mode</menu:label>
<menu:content>
<%= for item <- 0..5 do %>
<button>Option #<%= item %></button>
<% end %>
</menu:content>
</menu>
```
The engine would synthesize the above when a slot is used outside of a component by looking up at the nearest parent element.
```html
<menu>
<:label>Change Mode</:label>
<:content>
<%= for item <- 0..5 do %>
<button>Option #<%= item %></button>
<% end %>
</:content>
</menu>
```
https://user-images.githubusercontent.com/13581484/214320105-13ff1f22-16fe-414c-b02a-1d237be47a1a.mov

Add `Menu` and prototype for slot syntax

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/ViewModel.swift
Sources/LiveViewNative/Views/Controls and Indicators/Value Inputs/Slider.swift

Closes #69 
This builds on the prefixed children of #150 
I also added a `FormValue` conformance to `Double`.
```html
<slider name="number" upper-bound={10} step={1}>
<slider:label>
<text>Stepped</text>
</slider:label>
</slider>
<slider name="number" lower-bound={5} upper-bound={10}>
<text>Smooth</text>
<slider:minimum-value-label>
<text>Min</text>
</slider:minimum-value-label>
<slider:maximum-value-label>
<text>Max</text>
</slider:maximum-value-label>
</slider>
```
https://user-images.githubusercontent.com/13581484/214359261-dfb4bb22-3ff1-4a2a-b93d-29c1178cd028.mov

Add `Slider`

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Controls and Indicators/Value Inputs/Stepper.swift
Tests/RenderingTests/ValueInputTests.swift

Closes #70 
You can specify a `lower-bound`, `upper-bound`, and `step`. The `step` defaults to `1`.
```html
<phx-form id="color-form" phx-change="update_color">
<circle fill-color={@color} modifiers={@native |> frame(width: 50, height: 50)} />
<text font="caption" color="system-secondary">
<%= @r %> <%= @g %> <%= @b %>
</text>
<stepper name="r" step={10} upper-bound="255">Red</stepper>
<stepper name="g" step={10} lower-bound="0" upper-bound="255">Green</stepper>
<stepper name="b" step="10" lower-bound="0" upper-bound="255">Blue</stepper>
</phx-form>
```
https://user-images.githubusercontent.com/13581484/215889958-a489b93f-60c9-4427-a1e3-c6df05cf9433.mp4

Add `Stepper`

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/CustomRegistry.swift
Sources/LiveViewNative/ViewModifierBuilder.swift
Sources/LiveViewNative/ViewTree.swift
Tests/LiveViewNativeTests/DecodeModifiersTest.swift

This refactors modifier handling to avoid the use of `AnyView`, which could impact performance.
Now, modifiers work more like elements. Custom registries should provide an `applyModifier(_:modifier:to:context:)` method to register custom modifier types:
```swift
struct MyRegistry: CustomRegistry {
static func applyModifier(_ type: ModifierType, modifier: Modifier<Self>, to content: some View, context: LiveContext<Self>) -> some View {
switch type {
case .myModifier:
content.modifier(MyCustomModifier(from: modifier))
}
}
}
```
Note that this will require some changes to the serialization in `live_view_native_swift_ui` (https://github.com/liveviewnative/live_view_native_swift_ui/pull/5), so that each parameter value is encoded as a string, similar to element attributes. These can then be …

Avoid `AnyView` in modifiers

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Text Input and Output/Label.swift
Tests/RenderingTests/TextTests.swift

Closes #44
The `icon` and `title` slots can be used to set the content:
```html
<label>
<:title>
<text>Lightning</text>
</:title>
<:icon>
<image system-name="bolt.fill" />
</:icon>
</label>
```
The `system-image` attribute can be used in place of an `icon` slot:
```html
<label system-image="bolt.fill">Lightning</label>
```
A few styles are also available:
```html
<label label-style="icon-only">
<text>This is ignored</text>
<:icon>
<image system-name="bolt.fill" />
</:icon>
</label>
```
The tests will probably fail until #158 is merged, which contains some fixes for slots.

Add `Label`

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Utils/DOM.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Section.swift
Tests/RenderingTests/CollectionContainerTests.swift

Closes #111 
```html
<section>
<:header>5 Items</:header>
<:content>
<%= for item <- 1..5 do %>
<text><%= item %></text>
<% end %>
</:content>
<:footer>Above are some important items, in the range 1-5.</:footer>
</section>
```
The default slot can also be used for the content:
```html
<section>
<:header>5 Items</:header>
<%= for item <- 1..5 do %>
<text><%= item %></text>
<% end %>
<:footer>Above are some important items, in the range 1-5.</:footer>
</section>
```
On macOS, with the `sidebar` list style sections can be marked `collapsible`.
On iOS, sidebar list sections are always collapsible and the modifier is unavailable.
```html
<section collapsible="true">
...
</section>
<section> ... </section>
```
https://user-images.githubusercontent.com/13581484/216371451-70a03e8a-ea01-4e07-a762-9 …

Add Section

---

Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/Environment.swift
Sources/LiveViewNative/FragmentEncoder.swift
Sources/LiveViewNative/LiveViewNative.docc/LiveViewNative.md
Sources/LiveViewNative/NavStackEntryView.swift
Sources/LiveViewNative/Property Wrappers/FormState.swift
Sources/LiveViewNative/Property Wrappers/LiveBinding.swift
Sources/LiveViewNative/Property Wrappers/ObservedElement.swift
Sources/LiveViewNative/ViewModel.swift
Sources/LiveViewNative/Views/PhxForm.swift
Tests/LiveViewNativeTests/FragmentEncoderTests.swift

This PR adds two things:
1. A proper, public API for handling events on the client
2. The real meat and potatoes: live bindings, a mechanism for two-way client/server bindings
~~The only thing that remains before this can be merged is integrating live bindings with `@FormState`. Form state elements currently always use the `value` attribute and store data either locally or in an `<phx-form>`. Once this is implemented, if the `value-binding` attribute is present, it will establish a live binding which will be used for storage.~~
Event handling uses Combine, which allows for cancelling previously created event handlers as well as easily listening for events from within the SwiftUI lifecycle (using `onReceive`).
Bindings must be declared on the server-side live view, in this example it's …

Live bindings and public event handling API

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Layout Containers/Groups/ControlGroup.swift
Tests/RenderingTests/GroupTests.swift

Closes #119 
```html
<text><%= @number %></text>
<control-group>
<control-group:label>
<label system-image="gear">Options</label>
</control-group:label>
<control-group:content>
<%= for item <- 1..5 do %>
<button phx-click="set_number" phx-value-number={item}>Item #<%= item %></button>
<% end %>
</control-group:content>
</control-group>
```
https://user-images.githubusercontent.com/13581484/217863551-9a659ceb-fe3a-4fd7-ac29-3a8f9957d4f6.mp4
This will become more useful once we have the `toolbar` modifier.

Add ControlGroup

---

Sources/LiveViewNative/LiveContext.swift
Sources/LiveViewNative/Property Wrappers/ObservedElement.swift

The first fix has to do with demangling Swift types at runtime, and seems to only be an issue in debug builds, not release, but it was untenably bad in debug. The second fixes ObservedElement views updating excessively.
Together, these bring the time for the same view update in my test from 700ms to about 60ms. In a release build, the time is about 40ms.
The test was selecting a new value in a 6-option picker that's backed by a live binding shared by 4 pickers.

Performance improvements when handling document updates

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Layout Containers/Lazy Stacks/LazyHStack.swift
Sources/LiveViewNative/Views/Layout Containers/Lazy Stacks/LazyVStack.swift

Closes #95, #96 
Lazy stacks don't create items until they will be on screen. This can be seen in the demo below, where the `AsyncImage` doesn't load until the item is scrolled into view.
The `pinned-views` option automatically pins the `<section>` headers to the top of the scroll view, as can be seen in the demo as well.
https://user-images.githubusercontent.com/13581484/217910317-347c6c5b-93ed-4a44-9b34-7414e09447f0.mov
```html
<scroll-view>
<lazy-vstack pinned-views="section-headers">
<%= for {season, episodes} <- @episodes do %>
<section id={season |> Integer.to_string}>
<section:header>
<vstack spacing="0">
<divider />
<zstack alignment="leading">
<rectangle fill-color="system-white" modifiers={@native |> frame(height: 40)} />
<hstack modifiers={@native |> padding(all: 8)}>
<text …
```

Add Lazy Stacks

---

Sources/LiveViewNative/Views/Layout Containers/Collection Containers/List.swift

This adds support for `List.selection` using `LiveBinding`. You can specify a String value or a set of String values as the selection.
```html
<list selection="selection">
<%= for item <- 1..10 do %>
<text id={item |> Integer.to_string}><%= item %></text>
<% end %>
</list>
```
```ex
defmodule ... do
bindings(selection: ["1", "3", "5"], single_value_selection: "1", empty_single_selection: nil)
...
end
```
https://user-images.githubusercontent.com/13581484/218798033-150c6b1e-b9c9-4baa-9636-3a899be3153e.mp4
If you start with a value of `nil` or a single string, it will only allow one row to be selected at a time.

List selection support

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Utils/Color.swift
Sources/LiveViewNative/Views/Controls and Indicators/Pickers/ColorPicker.swift
Tests/RenderingTests/PickerTests.swift

Closes #75. Implemented using LiveBinding, as I'm not sure if color should be a `FormValue` primitive.
```html
<z-stack alignment="bottom">
<rectangle fill-color={TestBedWeb.IndexLive.fill_color(@color_selection)} />
<group-box modifiers={@native |> padding(all: 16)}>
<color-picker selection="color_selection">
Background
</color-picker>
</group-box>
</z-stack>
```
```ex
defmodule ... do
bindings(color_selection: Macro.escape(%{ "r" => 1.0, "g" => 1.0, "b" => 1.0 }))
...
end
```
https://user-images.githubusercontent.com/13581484/218838435-f30d1212-8842-4aa3-a363-528931840a2f.mp4

Add ColorPicker

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Modifiers/Grid/GridCellAnchorModifier.swift
Sources/LiveViewNative/Modifiers/Grid/GridCellColumnsModifier.swift
Sources/LiveViewNative/Modifiers/Grid/GridCellUnsizedAxesModifier.swift
Sources/LiveViewNative/Modifiers/Grid/GridColumnAlignmentModifier.swift
Sources/LiveViewNative/Utils/Alignment.swift
Sources/LiveViewNative/Utils/Axis.swift
Sources/LiveViewNative/Utils/UnitPoint.swift
Sources/LiveViewNative/Views/Layout Containers/Grids/Grid.swift
Sources/LiveViewNative/Views/Layout Containers/Grids/GridRow.swift
Sources/LiveViewNative/Views/Layout Containers/Scroll Views/ScrollView.swift
Sources/LiveViewNative/Views/Layout Containers/Stacks/HStack.swift
Sources/LiveViewNative/Views/Layout Containers/Stacks/VStack.swift
Tests/RenderingTests/GridTests.swift

Closes #97 and #98.
```html
<grid modifiers={@native |> frame(width: 350, height: 300)}>
<grid-row alignment="top">
<text>Row 1</text>
<%= for _ <- 1..2 do %>
<rectangle fill-color="system-red" />
<% end %>
</grid-row>
<divider />
<grid-row>
<text>Row 2</text>
<%= for _ <- 1..5 do %>
<rectangle fill-color="system-green" />
<% end %>
</grid-row>
<divider />
<grid-row alignment="bottom">
<text>Row 3</text>
<%= for _ <- 1..4 do %>
<rectangle fill-color="system-blue" />
<% end %>
</grid-row>
</grid>
```
A few modifiers need to be implemented:

Implement Grid/GridRow

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Modifiers/TagModifier.swift
Sources/LiveViewNative/Property Wrappers/LiveBinding.swift
Sources/LiveViewNative/Views/Controls and Indicators/Pickers/Picker.swift
Tests/RenderingTests/PickerTests.swift

Closes #72 
Right now, the tag modifier (and thus picker values) are limited to strings. I'd like to allow more complex types or any FormValue-conforming type in the future, but SwiftUI is really picky about the type of the picker's selection binding and the value passed into `.tag` lining up (e.g., if the binding is for a `String?` and the type passed into tag is a non-optional `String`, SwiftUI will think that there are picker options without tags).
Also, the [multi-source Picker initializers](https://developer.apple.com/documentation/swiftui/picker/init(sources:selection:content:label:)) aren't supported, since LVN doesn't have a concept of passing unspecified types and keypaths over the wire.
```html
<%= for style <- ["inline", "menu", "navigation-link", "segmented"] do %>
<picker …
```

Add Picker

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Utils/GridItem.swift
Sources/LiveViewNative/Utils/PinnedScrollableViews.swift
Sources/LiveViewNative/Views/Layout Containers/Lazy Grids/LazyHGrid.swift
Sources/LiveViewNative/Views/Layout Containers/Lazy Grids/LazyVGrid.swift
Sources/LiveViewNative/Views/Layout Containers/Lazy Stacks/LazyHStack.swift
Sources/LiveViewNative/Views/Layout Containers/Lazy Stacks/LazyVStack.swift
Tests/RenderingTests/GridTests.swift

Closes #99, #100, #101
Currently, the `columns`/`rows` attribute uses a custom Elixir `GridItem` type in a list, which then needs to be JSON encoded manually. This could be a special case in the engine to JSON encode these particular attributes automatically.
```html
<lazy-v-grid columns={
Jason.encode! [
LiveViewNativeSwiftUi.Types.GridItem.adaptive(10, 100),
LiveViewNativeSwiftUi.Types.GridItem.fixed(250),
LiveViewNativeSwiftUi.Types.GridItem.flexible()
]
}>
...
</lazy-v-grid>
```
Alternatively, the columns could be specified using elements:
```html
<lazy-v-grid>
<lazy-v-grid:columns>
<adaptive minimum="10" maximum="100" />
<fixed size="250" />
<flexible />
</lazy-v-grid:columns>
</lazy-v-grid>
```
<details>
<summary>Demo Code</summary>
```html
<vstack spacing="0">
<hstack …
```

Add Lazy Grids

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Layout Containers/Sizing/ViewThatFits.swift
Tests/RenderingTests/LayoutContainerTests.swift

Closes #109.
Chooses the first content that fits within the available space.
```html
<hstack>
<image system-name="person.circle.fill" />
<view-that-fits axes="horizontal">
<text>Long post content, takes up most of the space</text>
<text>Shorter version</text>
</view-that-fits>
</hstack>
```
But if we limit the size to `200`, it will choose the shorter version:
```html
<hstack modifiers={@native |> frame(width: 200)}>
...
</hstack>
```

Add ViewThatFits

---

lib/live_view_native_swift_ui/types/grid_item.ex

@carson-katri Moving https://github.com/liveviewnative/live_view_native_swift_ui/pull/8 to here as part of the monorepo migration (see https://github.com/liveviewnative/liveview-client-swiftui/pull/193)

Add grid item

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Layout Containers/Groups/ControlGroup.swift
Sources/LiveViewNative/Views/Layout Containers/Groups/DisclosureGroup.swift
Tests/RenderingTests/GroupTests.swift

Closes #206 
A live binding can be used with the `is-expanded` attribute, allowing the group to be opened/closed in sync with another action, such as a toggle.
```html
<toggle value-binding="is_on" />
<disclosure-group modifiers={padding(@native, all: 16)} is-expanded="is_on">
<disclosure-group:label>
This is the label
</disclosure-group:label>
<text>Hello, world!</text>
</disclosure-group>
```
https://user-images.githubusercontent.com/13581484/220772820-570fef31-d528-4e56-a4e4-d887f285d3be.mp4
It also plays well with `List` out of the box:
```html
<list>
<disclosure-group id="root">
<disclosure-group:label>
📂 Documents
</disclosure-group:label>
<disclosure-group>
<disclosure-group:label>
📂 Projects
</disclosure-group:label>
<disclosure-group>
<disclosure-group:label>
📂 LiveViewNative …
```

Add DisclosureGroup

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Modifiers/FontWeight.swift
lib/live_view_native_swift_ui/modifiers/font_weight.ex
lib/live_view_native_swift_ui/platform.ex

Adds support for the [`fontWeight`](https://developer.apple.com/documentation/swiftui/view/fontweight(_:)) modifier:
```elixir
<vstack id="modifiers-ios">
<text modifiers={font_weight(@native, weight: :black)}>Black</text>
<text modifiers={font_weight(@native, weight: :bold)}>Bold</text>
<text modifiers={font_weight(@native, weight: :heavy)}>Heavy</text>
<text modifiers={font_weight(@native, weight: :light)}>Light</text>
<text modifiers={font_weight(@native, weight: :medium)}>Medium</text>
<text modifiers={font_weight(@native, weight: :regular)}>Regular</text>
<text modifiers={font_weight(@native, weight: :semibold)}>Semibold</text>
<text modifiers={font_weight(@native, weight: :thin)}>Thin</text>
<text modifiers={font_weight(@native, weight: :ultra_light)}>Ultra Light</text>
</vstack> …
```

Add font weight modifier

---

Sources/LiveViewNative/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Layout Containers/Forms/LabeledContent.swift
Tests/RenderingTests/FormTests.swift

Closes #116 
You can initialize with a View, or with a value/format like the Text view accepts.
```html
<form>
<labeled-content value={3_400} format="number">Δv</labeled-content>
<labeled-content value={6_000_000} format="currency" currency-code="usd">Cost</labeled-content>
<labeled-content value={DateTime.utc_now()} format="date-time">Launch Date</labeled-content>
<labeled-content>
<labeled-content:label>Part Count</labeled-content:label>
<labeled-content:content>
<hstack>
<button phx-click="decrement">-</button>
<divider />
<button phx-click="increment">+</button>
</hstack>
</labeled-content:content>
</labeled-content>
</form>
```

Add `LabeledContent`

---

Sources/LiveViewNative/Registries/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/HSplitView.swift
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/VSplitView.swift

Closes #126, #127 
These Views are only available on macOS.
```html
<v-split-view>
<h-split-view>
<rectangle fill-color="system-red" />
<rectangle fill-color="system-orange" />
</h-split-view>
<h-split-view>
<rectangle fill-color="system-green" />
<rectangle fill-color="system-blue" />
</h-split-view>
</v-split-view>
```
https://user-images.githubusercontent.com/13581484/222525147-28d16bae-95db-4346-a64f-72ef4473f6d0.mov

Add H/VSplitView

---

Sources/LiveViewNative/Registries/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Controls and Indicators/Links/TextFieldLink.swift

Closes #66 
This View is only available on watchOS. When tapped, a watchOS text input will be presented, and when closed the value is sent to the server, either to a form or binding.
```html
<scroll-view>
<phx-form id="my-form" phx-submit="send_message">
<text-field-link name="body">
Message
</text-field-link>
<phx-submit-button modifiers={@native |> tint(color: "system-blue")}>Send</phx-submit-button>
</phx-form>
<divider modifiers={@native |> padding(all: 8)} />
<v-stack>
<v-stack>
<%= for message <- @messages do %>
<text id={message.id}><%= message.body %></text>
<% end %>
</v-stack>
</v-stack>
</scroll-view>
```
https://user-images.githubusercontent.com/13581484/222529279-4ff68ed4-db65-4601-91f8-504feb98234a.mp4

Add TextFieldLink

---

Sources/LiveViewNative/Registries/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Controls and Indicators/Buttons/PasteButton.swift

Closes #62 
`PasteButton` doesn't seem to render in snapshot tests, so I haven't included one. I'm not sure why it doesn't though.
When #159 is merged I will update this to use the `@Event` wrapper for throttle/debounce/component support.
Currently this only supports pasting strings. It returns an array of strings to the event set with `phx-click`.
```html
<text><%= @pasted_value %></text>
<paste-button phx-click="paste_value" />
```
```ex
def handle_event("paste_value", %{ "value" => value }, socket) do
{:noreply, assign(socket, :pasted_value, hd(value))}
end
```
https://user-images.githubusercontent.com/13581484/222542188-f6f3b666-3abf-4f8c-a320-ec91e712dce2.mp4

Add PasteButton

---

Sources/LiveViewNative/Modifiers/RenameActionModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
Tests/RenderingTests/ButtonTests.swift
lib/live_view_native_swift_ui/modifiers/rename_action.ex
lib/live_view_native_swift_ui/platform.ex

This adds the `rename-button` View and associated `rename_action` modifier. When clicked, the button will trigger the event specified by `rename_action`, which can be declared on any of its parent Views.
> **Note** Support for the `target` option is waiting on #166 
Alternatively, `<rename-button>` could be implemented with the event being specified on its element with `phx-click`. However, this deviates from how SwiftUI declares this type of button. I assume they designed it like this because rename buttons often appear in multiple places but should trigger the same action?
```html
<text>
<%= if @is_on do %>
Renaming
<% else %>
Not Renaming
<% end %>
</text>
<v-stack modifiers={@native |> rename_action(event: "rename")}>
<rename-button />
</v-stack>
``` …

Add `RenameButton` and `renameAction`

---

Sources/LiveViewNative/Utils/UnitPoint.swift
Sources/LiveViewNative/ViewTree.swift
Sources/LiveViewNative/Views/Layout Containers/Scroll Views/ScrollView.swift
Tests/LiveViewNativeTests/DecodeUnitPointTests.swift

Closes #121 
This is intended to cover `ScrollViewReader`'s use cases. Pass the `scroll-position` attribute to `<scroll-view>` and optionally a unit point for the anchor. Any time the value changes, the View with that ID will be scrolled into frame.
Currently, no animations are provided. These could be enabled later with a `scroll-position-animation` attribute once we have an `Animation` type in the Elixir library.
I have also updated the builder so that any time a View has an `id` attribute it is given an `.id(_:)` modifier. This could also be refactored to be a normal modifier for more control over where it applies in the stack.
```html
<z-stack alignment="bottom">
<scroll-view scroll-position={@scroll_position} scroll-position-anchor={%LiveViewNativeSwiftUi.Types.UnitPoint{ x: 0, y: 0 …
```

Add scroll-position attribute

---

Sources/DocumentationExtensionGenerator/DocumentationExtensionGenerator.swift
Sources/LiveViewNative/LiveViewNative.docc/Shapes.md
Sources/LiveViewNative/LiveViewNative.docc/Shapes/Rectangle.md
Sources/LiveViewNative/Views/Shapes/Shape.swift

Shapes are excluded from the automatic extension generation, since there aren't structs for each shape. The shapes which have extensions with element initializers are documented on the extensions, and Rectangle is documented in a separate article.

Document shapes

---

Sources/LiveViewNative/Modifiers/BoldModifier.swift
Sources/LiveViewNative/Modifiers/FontWeightModifier.swift
Sources/LiveViewNative/Modifiers/ItalicModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
lib/live_view_native_swift_ui/modifiers/bold.ex
lib/live_view_native_swift_ui/modifiers/italic.ex
lib/live_view_native_swift_ui/platform.ex

Adds support for [bold](https://developer.apple.com/documentation/swiftui/text/bold()) and [italic](https://developer.apple.com/documentation/swiftui/text/italic()) modifiers. Setting font weight is already possible since https://github.com/liveview-native/liveview-client-swiftui/pull/202 but https://github.com/liveview-native/liveview-client-swiftui/issues/183 called for implementing `bold`.
```heex
<VStack>
<Text>This text is normal</Text>
<Text modifiers={bold(@native)}>This text is bold</Text>
<Text modifiers={italic(@native)}>This text is italic</Text>
<Text modifiers={@native |> bold() |> italic()}>This text is bold and italic</Text>
</VStack>
```

Add bold and italic modifiers

---

Sources/LiveViewNative/Modifiers/AspectRatioModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Images/Image.swift
lib/live_view_native_swift_ui/modifiers/aspect_ratio.ex
lib/live_view_native_swift_ui/platform.ex

Adds support for the [aspectRatio](https://developer.apple.com/documentation/swiftui/view/aspectratio(_:contentmode:)-771ow) modifier:
```heex
<VStack>
<Spacer />
<Image name="AspectTest" resizable modifiers={@native |> aspect_ratio(content_mode: "fit") |> frame(width: 300, height: 225)} />
<Spacer />
<Image name="AspectTest" resizable modifiers={@native |> aspect_ratio(content_mode: "fill") |> frame(width: 300, height: 225)} />
<Spacer />
</VStack>
```

Add aspect ratio modifier

---

.gitignore
Plugins/SortDocumentationJSONPlugin/SortDocumentationJSONPlugin.swift
util/build_docs.sh
util/build_swift_docc_render.sh

This adds a script that builds `swift-docc-render` and pushes the `dist` folder to the `swift-docc-render` branch of this repo.
Then in the `build_docs` script, that branch is cloned and used as the `DOCC_HTML_DIR`.
This will enable us to update the Vue site whenever necessary, without building it for every documentation change.

Build `swift-docc-render` and use for docs

---

Sources/LiveViewNative/Modifiers/Animations Modifiers/TransitionModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
Sources/LiveViewNative/Utils/AnyTransition.swift
Sources/LiveViewNative/Utils/Edge.swift
Sources/LiveViewNative/ViewTree.swift
lib/live_view_native_swift_ui/modifiers/transition.ex
lib/live_view_native_swift_ui/platform.ex
lib/live_view_native_swift_ui/types/transition.ex

Closes #214 
This adds the `transition` modifier and `Transition` type that decodes to `AnyTransition`.
https://user-images.githubusercontent.com/13581484/230122494-5f0fb90f-ad80-47fd-b2a5-7dbb7b152a6d.mp4
```heex
<Picker value-binding="transition">
<Picker:label>
<Text>Transition</Text>
</Picker:label>
<Picker:content>
<Text id="opacity" modifiers={~s([{"type": "tag", "value": "opacity"}])}>
Opacity
</Text>
<Text id="slide" modifiers={~s([{"type": "tag", "value": "slide"}])}>
Slide
</Text>
<Text id="move" modifiers={~s([{"type": "tag", "value": "move"}])}>
Move Bottom
</Text>
<Text id="offset" modifiers={~s([{"type": "tag", "value": "offset"}])}>
Offset 100
</Text>
<Text id="scale" modifiers={~s([{"type": "tag", "value": "scale"}])}>
Scale
</Text>
<Text id="push" modifiers={~s([{"type": …
```

Add `transition` modifier

---

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/StrikethroughModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
lib/live_view_native_swift_ui/modifiers/strikethrough.ex
lib/live_view_native_swift_ui/platform.ex

Add `strikethrough` modifier

---

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/BoldModifier.swift
Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/ItalicModifier.swift
lib/live_view_native_swift_ui/modifiers/bold.ex
lib/live_view_native_swift_ui/modifiers/italic.ex

This fixes the warnings from the `BoldModifier` and `ItalicModifier` initializers. I also added the `active` property to these modifiers.

Fix build warnings and add `active` to bold/italic

---

Sources/LiveViewNative/Modifiers/View Configuration Modifiers/StatusBarHiddenModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
lib/live_view_native_swift_ui/modifiers/status_bar_hidden.ex
lib/live_view_native_swift_ui/platform.ex

Adds [statusBarHidden](https://developer.apple.com/documentation/swiftui/view/statusbarhidden(_:)). With:
```heex
<VStack nav-title="SwiftUI Demo" modifiers={status_bar_hidden(@native, hidden: true)}>
<Text>Hello World</Text>
</VStack>
```
Without:
```heex
<VStack nav-title="SwiftUI Demo" modifiers={status_bar_hidden(@native, hidden: false)}>
<Text>Hello World</Text>
</VStack>
```
Closes https://github.com/liveview-native/liveview-client-swiftui/issues/429

Add statusBarHidden modifier

---

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/TextCaseModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
lib/live_view_native_swift_ui/modifiers/text_case.ex
lib/live_view_native_swift_ui/platform.ex

Adds the [textCase](https://developer.apple.com/documentation/swiftui/view/textcase(_:)) modifier:
```heex
<VStack>
<Text>This text is normal</Text>
<Text modifiers={text_case(@native, text_case: :uppercase)}>This text is uppercase</Text>
<Text modifiers={text_case(@native, text_case: :lowercase)}>This text is lowercase</Text>
</VStack>
```
Closes https://github.com/liveview-native/liveview-client-swiftui/issues/307.

Add textCase modifier

---

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/DynamicTypeSizeModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
lib/live_view_native_swift_ui/modifiers/dynamic_type_size.ex
lib/live_view_native_swift_ui/platform.ex

Adds the [dynamicTypeSize](https://developer.apple.com/documentation/swiftui/view/dynamictypesize(_:)-1m2tf) modifier:
```heex
<VStack>
<Text id="dynamic_type_x_small" modifiers={dynamic_type_size(@native, size: :x_small)}>x_small</Text>
<Text id="dynamic_type_small" modifiers={dynamic_type_size(@native, size: :small)}>small</Text>
<Text id="dynamic_type_medium" modifiers={dynamic_type_size(@native, size: :medium)}>medium</Text>
<Text id="dynamic_type_large" modifiers={dynamic_type_size(@native, size: :large)}>large</Text>
<Text id="dynamic_type_x_large" modifiers={dynamic_type_size(@native, size: :x_large)}>x_large</Text>
<Text id="dynamic_type_xx_large" modifiers={dynamic_type_size(@native, size: :xx_large)}>xx_large</Text>
<Text id="dynamic_type_xxx_large" …
```

Add dynamicTypeSize modifier

---

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/MonospacedDigitModifier.swift
Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/MonospacedModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
lib/live_view_native_swift_ui/modifiers/monospaced.ex
lib/live_view_native_swift_ui/modifiers/monospaced_digit.ex
lib/live_view_native_swift_ui/platform.ex

Adds the [monospaced](https://developer.apple.com/documentation/swiftui/view/monospaced(_:)) and [monospacedDigit](https://developer.apple.com/documentation/swiftui/view/monospaceddigit()) modifiers:
```heex
<VStack>
<Label modifiers={monospaced(@native, is_active: true)}>This text is monospaced</Label>
<Label modifiers={monospaced(@native, is_active: false)}>This text is not</Label>
<Label modifiers={monospaced_digit(@native)}>1234567890</Label>
<Label>1234567890</Label>
</VStack>
```
Closes https://github.com/liveview-native/liveview-client-swiftui/issues/304
Closes https://github.com/liveview-native/liveview-client-swiftui/issues/305

Add monospaced and monospacedDigit modifiers

---

Sources/LiveViewNative/Modifiers/View Configuration Modifiers/StatusBarHiddenModifier.swift
Tests/RenderingTests/PickerTests.swift

There was a workaround that is no longer needed in the test.

Fix `testPicker`

---

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/TextFieldStyleModifier.swift
Sources/LiveViewNative/Registries/BuiltinRegistry.swift
Sources/LiveViewNative/Views/Text Input and Output/SecureField.swift
Sources/LiveViewNative/Views/Text Input and Output/TextField.swift
Sources/LiveViewNative/Views/Text Input and Output/TextFieldProtocol.swift
lib/live_view_native_swift_ui/modifiers/text_field_style.ex
lib/live_view_native_swift_ui/platform.ex

Closes #479 
Should the styles be underscored instead of dashed? Currently we can set the style of the field two ways:
```html
<TextField text-field-style="rounded-border" />
<TextField modifiers={text_field_style(@native, style: :"rounded-border")} />
```
If we make it underscored for both, the atom wouldn't need quotes. Could also use a different name for the attribute vs. modifier method.

Add `text_field_style` modifier

---

Sources/LiveViewNative/Registries/BuiltinRegistry.swift

Closes #806
The root cause of the on-device crash is that the stack grows by an absurd amount in the `ViewTreeBuilder.fromNodes` call—so much so that we exceed the 1MB stack limit.
In `fromNodes`, the stack grows by about 10KB per call to `f` in the function, regardless of whether the call is actually made. And with 55 call sites, that puts us at ~550KB stack growth and over the limit. I'm not entirely certain, but I suspect that's all coming from type metadata for the massive `_ConditionalContent` that is the result of `BuiltinRegistry.lookup` (commenting out most of the switch cases in that method dramatically reduces the stack size).
We can workaround this by moving that giant lookup switch to a separate view type, which effectively splits the stack growth into two separate phases—one …

Workaround for exceeding stack limit on iOS devices

---

Sources/LiveViewNative/Modifiers/Gestures Modifiers/GestureModifier.swift
Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/CoordinateSpaceModifier.swift
Sources/LiveViewNative/Property Wrappers/Event.swift
Sources/LiveViewNative/Utils/CoordinateSpace.swift
Sources/LiveViewNative/Utils/Gesture/AnyGesture.swift
Sources/LiveViewNative/Utils/Gesture/GestureMask.swift
lib/live_view_native_swift_ui/modifiers/coordinate_space.ex
lib/live_view_native_swift_ui/modifiers/gesture.ex
lib/live_view_native_swift_ui/types/gesture.ex

This adds support for gestures with the `gesture` modifier. This modifier automatically maps to the `gesture`, `highPriorityGesture` or `simultaneousGesture` modifier based on the priority level.
Instead of implementing `onTapGesture`/`onLongPressGesture` the more general `gesture` modifier can be used with `:tap`, `:spatial_tap`, or `:long_press` gesture types.
Closes #556
Closes #557 
Closes #556 
Closes #551 
Closes #553

Add `gesture` modifier and `AnyGesture`

---

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/TextFieldStyleModifier.swift
lib/live_view_native_swift_ui/modifiers/text_field_style.ex

@carson-katri I was testing other `TextField` modifiers and ran into this mismatch between the Elixir and Swift values. Underscore is what I'm seeing used elsewhere so I changed it to that.

Fix mismatch between Elixir and Swift values for `text_field_style`

---

Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/OffsetModifier.swift
lib/live_view_native_swift_ui/modifiers/offset.ex

Adds the [offset](https://developer.apple.com/documentation/swiftui/view/offset(x:y:)) modifier. I didn't include the `CGSize` constructor as it seemed redundant in this case, but let me know if you think it should be supported:
```heex
<VStack>
<Text>This text is not offset</Text>
<Text modifiers={offset(@native, x: 4, y: 8)}>This text is slightly offset</Text>
<Text modifiers={offset(@native, x: 32, y: 64)}>This text is very offset</Text>
</VStack>
```
Closes https://github.com/liveview-native/liveview-client-swiftui/issues/497

Add offset modifier

---

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/BorderModifier.swift
lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/border.ex

This PR adds the [border](https://developer.apple.com/documentation/swiftui/view/border(_:width:)) drawing and graphics modifier:
```heex
<VStack id="border">
<Text modifiers={border(@native, content: {:color, :purple}, width: 4)}>
Purple border inside the view bounds.
</Text>
<Text modifiers={@native |> padding(all: 4) |> border(content: {:color, :purple}, width: 4)}>
Purple border outside the view bounds.
</Text>
</VStack>
```
Closes #264

Add `border` modifier

---

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ForegroundColorModifier.swift
lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/foreground_color.ex

This PR adds support for the [foregroundColor](https://developer.apple.com/documentation/swiftui/view/foregroundcolor(_:)) drawing and graphics modifier:
```heex
<VStack id="foreground_color">
<Text modifiers={foreground_color(@native, color: "#7b1fa2")}>
This text is colored with a hex code
</Text>
<Text modifiers={foreground_color(@native, color: :mint)}>
This text is colored with a standard color
</Text>
<Text modifiers={foreground_color(@native, color: :primary)}>
This text is colored with a system color
</Text>
</VStack>
```
https://user-images.githubusercontent.com/5893007/234078315-d6a3911c-007c-4c9d-9079-b24b08572fbd.mov
Closes #258

Add `foreground_color` modifier

---

Sources/LiveViewNative/Modifiers/View Configuration Modifiers/HiddenModifier.swift
lib/live_view_native_swift_ui/modifiers/view_configuration/hidden.ex

This PR adds the [hidden](https://developer.apple.com/documentation/swiftui/view/hidden()) view configuration modifier. It uses a `isActive` argument to toggle the modifier on and off which isn't defined by the SwiftUI spec, but it seemed useful to be able to conditionally hide and show based on LiveView assigns (other modifiers with 0-arity do this, like `BoldModifier` and `ItalicModifier`):
```elixir
defmodule ScratchboardWeb.HiddenLive do
use Phoenix.LiveView
use LiveViewNative.LiveView
@impl true
def render(assigns) do
render_native(assigns)
end
@impl true
def mount(_params, _session, socket) do
Process.send_after(self(), :tick, 500)
{:ok, assign(socket, hidden: false)}
end
def handle_info(:tick, socket) do
Process.send_after(self(), :tick, 500)
{:noreply, assign(socket, hidden: …
```

Add `hidden` modifier

---

Sources/LiveViewNative/Modifiers/Layout Fundamentals Modifiers/ZIndexModifier.swift
lib/live_view_native_swift_ui/modifiers/layout_fundamentals/z_index.ex

This PR adds support for the [zIndex](https://developer.apple.com/documentation/swiftui/view/zindex(_:)) modifier:
```heex
<ZStack id="z_index">
<ZStack>
<% # Without setting z_index, elements are layered according to order in the template %>
<Circle modifiers={@native |> frame(width: 64, height: 64) |> foreground_style(primary: {:color, :red})} />
<Circle modifiers={@native |> frame(width: 64, height: 64) |> offset(x: 8, y: 8) |> foreground_style(primary: {:color, :green})} />
<Circle modifiers={@native |> frame(width: 64, height: 64) |> offset(x: 16, y: 16) |> foreground_style(primary: {:color, :blue}) } />
</ZStack>
<ZStack modifiers={@native |> offset(x: 0, y: 128)}>
<% # Using z_index, we can override the default layering  %>
<Circle modifiers={@native |> z_index(value: 3) |> …
```

Add `z_index` modifier

---

Sources/LiveViewNative/Modifiers/Images Modifiers/ImageScaleModifier.swift
lib/live_view_native_swift_ui/modifiers/images/image_scale.ex

This PR adds support for the [imageScale](https://developer.apple.com/documentation/swiftui/view/imagescale(_:)) modifier:
```heex
<VStack>
<HStack modifiers={image_scale(@native, scale: :small)}>
<Image system-name="heart.fill"></Image>
<Text>Small</Text>
</HStack>
<HStack modifiers={image_scale(@native, scale: :medium)}>
<Image system-name="heart.fill"></Image>
<Text>Medium</Text>
</HStack>
<HStack modifiers={image_scale(@native, scale: :large)}>
<Image system-name="heart.fill"></Image>
<Text>Large</Text>
</HStack>
</VStack>
```

Add `image_scale` modifier

---

Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/PaddingModifier.swift
Sources/LiveViewNative/Modifiers/Lists Modifiers/ListRowInsetsModifier.swift
Sources/LiveViewNative/Utils/Edge.swift
Sources/LiveViewNative/Utils/EdgeInsets.swift
Tests/LiveViewNativeTests/DecodeModifiersTest.swift
lib/live_view_native_swift_ui/modifiers/layout_adjustments/padding.ex
lib/live_view_native_swift_ui/types/edge_insets.ex
lib/live_view_native_swift_ui/types/edge_set.ex

This refactors the padding modifier to make accessing the system padding amount possible.
```html
<Text modifiers={padding(@native)}>Use the system padding</Text>
<Text modifiers={padding(@native, edges: :horizontal, length: 10)}>Affect specific edges</Text>
<Text modifiers={padding(@native, insets: [top: 8, bottom: 16])}>Use EdgeInsets</Text>
```

Refactor and document padding modifier

---

Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/SafeAreaInsetModifier.swift
lib/live_view_native_swift_ui/modifiers/safe_area_inset.ex

Closes #510
https://user-images.githubusercontent.com/13581484/230462561-c3f2afa2-fd74-462e-a8c4-6db2d3da3c14.mp4
```html
<List modifiers={safe_area_inset(@native, edge: :bottom, content: :bottom_bar)}>
<%= for item <- 1..25 do %>
<Text id={Integer.to_string(item)}><%= item %></Text>
<% end %>
<safe_area_inset:bottom_bar id="bottom_bar">
<GroupBox modifiers={padding(@native, all: 32)}>
<GroupBox:label>
<HStack>
<Text font-weight="bold" font="title2">Bottom Bar</Text>
<Spacer />
</HStack>
</GroupBox:label>
<Text>
This will allow the list to scroll further up so no rows are covered.
</Text>
</GroupBox>
</safe_area_inset:bottom_bar>
</List>
```

Add `safe_area_inset` modifier

---

Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/FontDesignModifier.swift
lib/live_view_native_swift_ui/modifiers/text_input_and_output/font_design.ex

Adds the [fontDesign](https://developer.apple.com/documentation/swiftui/view/fontdesign(_:)) text input and output modifier:
```heex
<VStack id="font_design">
<Text modifiers={font_design(@native, design: :default)}>This text is default</Text>
<Text modifiers={font_design(@native, design: :monospaced)}>This text is monospaced</Text>
<Text modifiers={font_design(@native, design: :rounded)}>This text is rounded</Text>
<Text modifiers={font_design(@native, design: :serif)}>This text is serif</Text>
</VStack>
```
Closes #300

Add `font_design` modifier

---

Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
lib/live_view_native_swift_ui/platform.ex

This PR changes the `platform_id` to be more semantically correct. If you're rendering SwiftUI views in a LiveView Native project using template files, you'll need to rename them to use the `.swiftui.heex` extension rather than the `.ios.heex` extension they have been using up until now.

Change `platform_id` from `ios` to `swiftui`

---

Sources/LiveViewNative/Coordinators/LiveConnectionError.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/ErrorView.swift
Sources/LiveViewNative/LiveView.swift

If the initial parse failed, there was no clear indication of what the issue was. The messages are improved in the PR to be more visible and descriptive.

Improve connection error messages

---

Sources/BuiltinRegistryGenerator/BuiltinRegistryGenerator.swift
Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/FontDesignModifier.swift
Sources/LiveViewNative/ViewModifierBuilder.swift

If an `@available` attribute is applied to a View or ViewModifier, it will be wrapped in `if #available`. This required some additions to the `ViewModifierBuilder`. Availability checks should be avoided if possible because they require type erasure. I'm not sure if the compiler automatically strips them if the deployment target is higher, but I assume it would.

Support availability checks in BuiltinRegistryGenerator

---

util/encode_modifiers.exs

The tool can be used when writing tests for modifiers to generate the JSON for a modifier stack.
For example, running the following command:
```sh
elixir util/encode_modifiers.exs "@native |> frame(width: 100, height: 100)"
```
will produce this JSON output, which can be pasted into the test:
```
[{&quot;alignment&quot;:null,&quot;height&quot;:100.0,&quot;type&quot;:&quot;frame&quot;,&quot;width&quot;:100.0}]
```

Add tool for JSON encoding modifier stack

---

Sources/LiveViewNative/Coordinators/LiveConnectionError.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/ErrorModifier.swift
Sources/LiveViewNative/ErrorView.swift
Sources/LiveViewNative/LiveView.swift
Sources/LiveViewNative/Modifiers/Animations Modifiers/MatchedGeometryEffectModifier.swift
Sources/LiveViewNative/Modifiers/Input Events Modifiers/HoverEffectModifier.swift
Sources/LiveViewNative/Modifiers/Navigation Modifiers/NavigationBarTitleDisplayModeModifier.swift
Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/KeyboardTypeModifier.swift
Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/TextInputAutocapitalizationModifier.swift
Sources/LiveViewNative/Modifiers/Toolbars Modifiers/ToolbarModifier.swift
Sources/LiveViewNative/NavStackEntryView.swift
Sources/LiveViewNative/Property Wrappers/FormState.swift
Sources/LiveViewNative/Property Wrappers/LiveBinding.swift
Sources/LiveViewNative/Registries/CustomRegistry.swift
Sources/LiveViewNative/ViewTree.swift
Sources/LiveViewNative/Views/Images/Image.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Table.swift
Sources/LiveViewNative/Views/Text Input and Output/Text.swift

`fatalError`/`preconditionFailure` calls are replaced with throwing methods or `ErrorView` whenever possible. This should prevent the app from requiring a restart whenever something simple goes wrong.
By default, errors are presented with an alert:
In the `CustomRegistry`, implement the `errorView(for:)` method to override this behavior:
```swift
struct AppRegistry: RootRegistry {
static func errorView(for error: Error) -> some View {
Label(error.localizedDescription, systemImage: "xmark.diamond.fill")
.bold()
.foregroundStyle(.red)
}
}
```

Remove fatalError wherever possible

---

Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
lib/live_view_native_swift_ui/platform.ex

This PR proposes including additional metadata through the connection params so that it can be available to the backend LiveView application. Currently this only includes the platform variant (iOS, iPadOS, macOS, watchOS or tvOS) which developers using LiveView Native might want to match on, but it could be expanded to include other information about the client device.

Add platform metadata to connection params

---

Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/LiveViewNative.docc/LiveViewNative.md
Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/AspectRatioModifier.swift
Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/BackgroundStyleModifier.swift
Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/BlendModeModifier.swift
Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/DrawingGroupModifier.swift
Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ForegroundStyleModifier.swift
Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/MaskModifier.swift
Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/TintModifier.swift
Sources/LiveViewNative/Modifiers/Input Events Modifiers/AllowsHitTestingModifier.swift
Sources/LiveViewNative/Modifiers/Input Events Modifiers/DigitalCrownAccessoryVisibilityModifier.swift
Sources/LiveViewNative/Modifiers/Input Events Modifiers/HoverEffectModifier.swift
Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/FrameModifier.swift
Sources/LiveViewNative/Modifiers/Lists Modifiers/DeleteDisabledModifier.swift
Sources/LiveViewNative/Modifiers/Lists Modifiers/ListRowSeparatorModifier.swift
Sources/LiveViewNative/Modifiers/Lists Modifiers/MoveDisabledModifier.swift
Sources/LiveViewNative/Modifiers/Navigation Modifiers/NavigationBarBackButtonHiddenModifier.swift
Sources/LiveViewNative/Modifiers/Navigation Modifiers/NavigationBarTitleDisplayModeModifier.swift
Sources/LiveViewNative/Modifiers/Navigation Modifiers/NavigationTitleModifier.swift
Sources/LiveViewNative/Modifiers/Scroll Views Modifiers/ScrollBounceBehaviorModifier.swift
Sources/LiveViewNative/Modifiers/Scroll Views Modifiers/ScrollIndicatorsModifier.swift
Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/LineSpacingModifier.swift
Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/SubmitLabelModifier.swift
Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/TextContentTypeModifier.swift
Sources/LiveViewNative/Modifiers/View Configuration Modifiers/HiddenModifier.swift
Sources/LiveViewNative/Modifiers/View Configuration Modifiers/PreferredColorSchemeModifier.swift
Sources/LiveViewNative/Views/Layout Containers/Groups/DisclosureGroup.swift
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/TabView.swift
Sources/LiveViewNative/Views/Text Input and Output/TextField.swift

I started this exercise to check that my own documentation was being generated correctly and ended up making a full pass to fix the low hanging fruit.
- Reduced the number of documentation generation errors from 62 to 14 by fixing references and writing a few more entries.
- Added `// TODO: Documentation` comments for structs that have no documentation.
There was a class of error I'm not sure how to fix. 6 of the remaining 14 are errors like this in trying to reference functions.
> /Registries/CustomRegistry.swift:31:7: warning: Topic reference 'decodeModifier(_:from:context:)-4cqvs' couldn't be resolved. No local documentation matches this reference.

Add and fix documentation

---

util/encode_modifiers.exs

@carson-katri Thanks for writing the utility. It was a big help.
Since we escape the entire input string in Swift, I thought it would make the tests easier to read and tweak if they weren't HTML encoded.
```
[{&quot;disable&quot;:true,&quot;type&quot;:&quot;autocorrection_disabled&quot;}]
[{&quot;font&quot;:{&quot;modifiers&quot;:[],&quot;properties&quot;:{&quot;design&quot;:&quot;serif&quot;,&quot;style&quot;:&quot;large_title&quot;},&quot;type&quot;:&quot;system&quot;},&quot;type&quot;:&quot;font&quot;}]
```
vs
```
[{"disable":true,"type":"autocorrection_disabled"}]
[{"font":{"modifiers":[],"properties":{"design":"serif","style":"large_title"},"type":"system"},"type":"font"}]
```
I also made the utility strip `///` so I could cut and paste multiline modifier chains from the doc …

HTML decode the output of `encode_modifiers`

---

Plugins/DocumentationExtensionGeneratorPlugin/DocumentationExtensionGeneratorPlugin.swift
Sources/LiveViewNative/LiveViewNative.docc/Shapes.md
Sources/LiveViewNative/Shape Modifiers/FillModifier.swift
Sources/LiveViewNative/Shape Modifiers/InsetModifier.swift
Sources/LiveViewNative/Shape Modifiers/OffsetShapeModifier.swift
Sources/LiveViewNative/Shape Modifiers/RotationModifier.swift
Sources/LiveViewNative/Shape Modifiers/ShapeModifier.swift
Sources/LiveViewNative/Shape Modifiers/SizeModifier.swift
Sources/LiveViewNative/Shape Modifiers/StrokeBorderModifier.swift
Sources/LiveViewNative/Shape Modifiers/StrokeModifier.swift
Sources/LiveViewNative/Shape Modifiers/TrimModifier.swift
Sources/LiveViewNative/Utils/Alignment.swift
Sources/LiveViewNative/Utils/FillStyle.swift
Sources/LiveViewNative/Utils/ShapeStyle/AnyShapeStyle.swift
Sources/LiveViewNative/Utils/StrokeStyle.swift
Sources/LiveViewNative/ViewTree.swift
Sources/LiveViewNative/Views/Shapes/Shape.swift
Tests/RenderingTests/Modifiers/ShapeModifiersTests.swift
lib/live_view_native_swift_ui/modifiers/shape/fill.ex
lib/live_view_native_swift_ui/modifiers/shape/inset.ex
lib/live_view_native_swift_ui/modifiers/shape/offset_shape.ex
lib/live_view_native_swift_ui/modifiers/shape/rotation.ex
lib/live_view_native_swift_ui/modifiers/shape/size.ex
lib/live_view_native_swift_ui/modifiers/shape/stroke.ex
lib/live_view_native_swift_ui/modifiers/shape/stroke_border.ex
lib/live_view_native_swift_ui/modifiers/shape/trim.ex
lib/live_view_native_swift_ui/types/fill_style.ex
lib/live_view_native_swift_ui/types/shape_style/shape_style.ex
lib/live_view_native_swift_ui/types/stroke_style.ex

This adds support for new modifiers that only apply to shapes. This can be used to apply `ShapeStyle` fills and strokes. It also adds support for other Shape modifiers like `trim` and `size`.
This requires handling modifiers within `Shape`. Here's an example of mixing modifiers together:
```heex
<Circle modifiers={
@native
|> trim(start_fraction: 0.5)
|> offset_shape(x: 50, y: 50)
|> size(width: 50, height: 50)
|> fill(style: {:color, :purple})
|> gesture(gesture: :tap, action: "tap")
} />
```
The modifiers would be applied as:
1. `trim` - handled internally by `Shape`
2. `offset_shape` - handled internally by `Shape`
3. `size` - handled internally by `Shape`
4. `fill` - handled internally by `Shape`, treated as the "final modifier" since it returns a `_ShapeView` not a `Shape`
5. …

Add support for Shape-specific modifiers

---

Sources/LiveViewNative/Modifiers/Menus and Commands/MenuIndicatorVisibilityModifier.swift
lib/live_view_native_swift_ui/modifiers/menus_and_commands/menu_indicator_visibility.ex

Closes #289
No rendering test for this one, since it does not seem to have any effect on iOS.

Add menuIndicatorVisibility modifier

---

Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ClipShapeModifier.swift
Sources/LiveViewNative/Utils/ShapeReference.swift
Sources/LiveViewNative/Views/Shapes/Shape.swift
Tests/RenderingTests/Modifiers/DrawingAndGraphicsModifiersTests.swift
lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/clip_shape.ex
lib/live_view_native_swift_ui/types/shape.ex

This also adds a new `ShapeReference` type that can be used to pass a shape as a parameter to a modifier.
It supports the system shapes (with any arguments), as well as shapes with modifiers via an element with the `template` attribute.
```html
<Text modifiers={@native |> clip_shape(shape: :circle)}>
Hello,
world!
</Text>
<Text modifiers={@native |> clip_shape(shape: :my_shape)}>
Hello, world!
<Rectangle template={:my_shape} modifiers={@native |> rotation(angle: {:degrees, 45})} />
</Text>
```

Add `clip_shape` modifier

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/NavStackEntryView.swift

This fixes navigation on macOS by moving the coordinator `.connect()`/`.reconnect()` calls out of a task modifier and into the `LiveSessionCoordinator`.

Refactor `.connect()` calls

---

Sources/LiveViewNative/Modifiers/Lists Modifiers/SwipeActionsModifier.swift
lib/live_view_native_swift_ui/modifiers/lists/swipe_actions.ex

This PR adds support for the [swipeActions](https://developer.apple.com/documentation/swiftui/view/swipeactions(edge:allowsfullswipe:content:)) List modifier.
```heex
<VStack id="swipe_actions">
<Text>
<%= @swipe_event_message %>
</Text>
<Spacer />
<List>
<%= for {item, is_unread?} <- [{"Foo", true}, {"Bar", false}, {"Baz", false}] do %>
<HStack
id={item}
modifiers={
@native
|> swipe_actions(edge: :leading, allows_full_swipe: false, content: :hello)
|> swipe_actions(edge: :trailing, allows_full_swipe: false, content: :delete)
|> swipe_actions(edge: :trailing, allows_full_swipe: false, content: :flag)
}>
<Text><%= item %></Text>
<swipe_actions:hello>
<%= if is_unread? do %>
<Button>
<Image system-name="envelope.badge" />
</Button>
<% else %>
<Button modifiers={tint(@native, color: …
```

Add `swipe_actions` modifier

---

Sources/LiveViewNative/Utils/Font.swift
Sources/LiveViewNative/Views/Accessibility/ScaledMetric.swift

Closes #242 
This is a property wrapper in SwiftUI, but I implemented it as a View here (similar to how the `NamespaceContext` view is implemented). The `@ScaledMetric` wrapper is used on the View and updates a `@LiveBinding` with the scaled value.

Add `ScaledMetric`

---

Sources/LiveViewNative/Utils/Font.swift
lib/live_view_native_swift_ui/types/font.ex

This fixes a bug with the `Font` type encoding incorrectly when using a `{:system, [size: n]}` value.
I've also added documentation around this form.

Fix system font with size encoding

---

Sources/LiveViewNative/Property Wrappers/Event.swift
Sources/LiveViewNative/Property Wrappers/LiveContext.swift
Sources/LiveViewNative/Utils/Selection.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/List.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Table.swift

This fixes 3 bugs with `List`:
1. Elements with `template={...}` were rendered as list items and required an `id`. They are now ignored.
2. If no `selection` attribute was present, selection was still possible but not sent to the backend. Now selection is disabled if the attribute is not set to a binding (this applies to `Table` as well)
3. If no `phx-delete`/`phx-move` event was provided, delete/move actions were still enabled. Now they are disabled unless the event attribute is set.

Fix template elements and selection in `List`

---

Package@swift-5.9.swift
Sources/LiveViewNative/LiveView.swift
Sources/LiveViewNative/Modifiers/Focus Modifiers/FocusScopeModifier.swift
Sources/LiveViewNative/Modifiers/Focus Modifiers/PrefersDefaultFocusModifier.swift
Sources/LiveViewNative/Registries/AggregateRegistry.swift
Sources/LiveViewNative/Registries/CustomRegistry.swift
Sources/LiveViewNative/Shape Modifiers/StrokeBorderModifier.swift
Sources/LiveViewNative/Utils/KeyEquivalent.swift
Sources/LiveViewNativeMacros/LiveViewNativeMacros.swift
Sources/LiveViewNativeMacros/RegistriesMacro.swift
Tests/LiveViewNativeMacrosTests/LiveViewNativeMacrosTests.swift

* Fixes a build error with Swift 5.9
* Uses the new `ContentUnavailableView` when connection fails as the default on 2023 platforms.
* Adds a new `#Registries` macro that generates the `Registries` typealias in an `AggregateRegistry`. This is a better alternative to the `Registry2/Registry3/...` types, which require manually creating variants for each number of registries.
<table>
<tr>
<th>Macro</th><th>Expanded</th>
</tr>
<tr>
<td>
```swift
struct AppRegistries: AggregateRegistry {
#Registries<
MyRegistry,
LiveFormsRegistry<Self>,
AVKitRegistry<Self>,
MapKitRegistry<Self>
>
}
```
</td>
<td>
```swift
struct AppRegistries: AggregateRegistry {
typealias Registries = _MultiRegistry<
AppRegistry,
_MultiRegistry<
LiveFormRegistry<Self>,
_MultiRegistry<
PhotoKitRegistry<Self>, …
```

Update for Swift 5.9

---

Package@swift-5.9.swift
Sources/LiveViewNative/LiveView.swift
Sources/LiveViewNative/Modifiers/Animations Modifiers/KeyframeAnimatorModifier.swift
Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ScaleEffectModifier.swift
Sources/LiveViewNative/Modifiers/Focus Modifiers/FocusScopeModifier.swift
Sources/LiveViewNative/Modifiers/Focus Modifiers/PrefersDefaultFocusModifier.swift
Sources/LiveViewNative/Modifiers/Layout Adjustments Modifiers/OffsetModifier.swift
Sources/LiveViewNative/Registries/AggregateRegistry.swift
Sources/LiveViewNative/Registries/CustomRegistry.swift
Sources/LiveViewNative/Shape Modifiers/StrokeBorderModifier.swift
Sources/LiveViewNative/Utils/Animation.swift
Sources/LiveViewNative/Utils/DOM.swift
Sources/LiveViewNative/Utils/KeyEquivalent.swift
Sources/LiveViewNative/ViewTree.swift
Sources/LiveViewNativeMacros/LiveViewNativeMacros.swift
Sources/LiveViewNativeMacros/RegistriesMacro.swift
Tests/LiveViewNativeMacrosTests/LiveViewNativeMacrosTests.swift
lib/live_view_native_swift_ui/modifiers.ex
lib/live_view_native_swift_ui/modifiers/animation/keyframe_animator.ex
lib/live_view_native_swift_ui/modifiers/drawing_and_graphics/scale_effect.ex
lib/live_view_native_swift_ui/types/animation/animation.ex
lib/live_view_native_swift_ui/types/animation/keyframe.ex
lib/live_view_native_swift_ui/types/animation/keyframe_properties.ex
lib/live_view_native_swift_ui/types/encoded_modifier_stack.ex

This adds support for keyframe animation to the `Animation` type, as well as a new `keyframe_animator` modifier.
It is available for iOS 17 and aligned releases.
```elixir
<Button phx-click="like">
<Image
modifiers={
@native
|> font(font: {:system, :large_title})
|> foreground_style(primary: {:color, :red})
|> keyframe_animator(
initial_value: 0.0,
trigger: "#{@liked}",
keyframes: [
{:linear, 0.0, [duration: 0.5]},
{:cubic, -15.0 * (:math.pi / 180.0), [duration: 0.1]},
{:cubic, 15.0 * (:math.pi / 180.0), [duration: 0.1]},
{:cubic, -15.0 * (:math.pi / 180.0), [duration: 0.1]},
{:cubic, 15.0 * (:math.pi / 180.0), [duration: 0.1]},
{:spring, 0.0, [duration: 0.3, spring: :bouncy]},
],
modifiers: @native |> rotation_effect(angle: {:radians, 0.0}, anchor: :center),
properties: [rotation_effect: …
```

Add Keyframe Animation

---

Package@swift-5.9.swift
Sources/LiveViewNative/LiveView.swift
Sources/LiveViewNative/Modifiers/Focus Modifiers/FocusScopeModifier.swift
Sources/LiveViewNative/Modifiers/Focus Modifiers/PrefersDefaultFocusModifier.swift
Sources/LiveViewNative/Registries/AggregateRegistry.swift
Sources/LiveViewNative/Registries/CustomRegistry.swift
Sources/LiveViewNative/Shape Modifiers/StrokeBorderModifier.swift
Sources/LiveViewNative/Utils/AnyTransition.swift
Sources/LiveViewNative/Utils/ContentTransition.swift
Sources/LiveViewNative/Utils/KeyEquivalent.swift
Sources/LiveViewNativeMacros/LiveViewNativeMacros.swift
Sources/LiveViewNativeMacros/RegistriesMacro.swift
Tests/LiveViewNativeMacrosTests/LiveViewNativeMacrosTests.swift
lib/live_view_native_swift_ui/types/content_transition.ex
lib/live_view_native_swift_ui/types/transition.ex

Symbol effects are available in iOS 17 and aligned releases. This extends our `transition` and `content_transition` modifiers to support the `symbol_effect` transition types.
```heex
<Image
system-name={if @show, do: "eye.fill", else: "eye.slash.fill"}
modifiers={
@native
|> content_transition(transition: :symbol_effect)
}
/>
```
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/8b821b65-c16d-466c-93ab-c05fd2455942

Add symbol effect transitions

---

mix.exs

Bumping to 0.0.8-rc.0 to test support for upcoming releases of [live_view_native](https://github.com/liveview-native/live_view_native) and [live_view_native_platform](https://github.com/liveview-native/live_view_native_platform):
https://hex.pm/packages/live_view_native/0.0.8-rc.0
https://hex.pm/packages/live_view_native_platform/0.0.7-rc.0

Bump mix.exs version to `0.0.8-rc.0`

---

Sources/LiveViewNative/ContentBuilder.swift
Sources/LiveViewNative/Property Wrappers/ObservedElement.swift
Sources/LiveViewNative/Utils/DOM.swift
Sources/LiveViewNative/Utils/ElixirDateFormats.swift

This adds a new API for supporting DSLs other than SwiftUI in add-on libraries.
Like `View` in SwiftUI, libraries such as Swift Charts and MapKit have protocols like `ChartContent` and `MapContent`.
Supporting building with these elements, along with their own modifiers, can take a lot of boilerplate and could cause things to fall out of sync if changes are not carefully made to each add-on library.
This moves the logic for these into a single protocol, `ContentBuilder` to avoid those problems.
The code to support a DSL is now very simple, and automatically handles the `modifiers` and `template` attributes.
```swift
struct ChartContentBuilder: ContentBuilder {
typealias Content = any ChartContent
enum TagName: String {
case barMark = "BarMark"
case plot = "Plot"
}
enum ModifierType: …
```

Add ContentBuilder API

---

Sources/LiveViewNative/LiveViewNative.docc/Resources/01-01-03-mix.exs

The tutorial repo pulls from the main branch, and should pull from the hex.pm versions to avoid issues with breaking code changes during LVN development. This changes the tutorial site code to fix that. I am not sure if this fixes the code that builds to https://github.com/liveview-native/ios-tutorial so if there is someplace else to fix that before it is pushed, please let me know and I will update this PR. AFAIK, elixir was already updated to 1.15 last week.

Update to use hex.pm for live_view_native and live_view_native_swiftui

---

Sources/LiveViewNative/ContentBuilder.swift
Sources/LiveViewNative/Modifiers/Drawing and Graphics Modifiers/ClipShapeModifier.swift
Sources/LiveViewNative/Modifiers/Layout Fundamentals Modifiers/BackgroundModifier.swift
Sources/LiveViewNative/Modifiers/Layout Fundamentals Modifiers/OverlayModifier.swift
Sources/LiveViewNative/Modifiers/Shapes Modifiers/ContainerShapeModifier.swift
Sources/LiveViewNative/Modifiers/View Styles Modifiers/ContentShapeModifier.swift
Sources/LiveViewNative/Utils/ShapeReference.swift

This type is used by some modifiers in add-on libraries, such as Swift Charts.

Make `ShapeReference` public

---

lib/live_view_native_swift_ui/modifiers/animation/animation.ex
lib/live_view_native_swift_ui/modifiers/animation/content_transition.ex
lib/live_view_native_swift_ui/modifiers/animation/transition.ex
lib/live_view_native_swift_ui/modifiers/controls_and_indicators/button_style.ex
lib/live_view_native_swift_ui/modifiers/controls_and_indicators/control_size.ex
lib/live_view_native_swift_ui/modifiers/controls_and_indicators/date_picker_style.ex
lib/live_view_native_swift_ui/modifiers/controls_and_indicators/default_wheel_picker_item_height.ex
lib/live_view_native_swift_ui/modifiers/controls_and_indicators/gauge_style.ex
lib/live_view_native_swift_ui/modifiers/controls_and_indicators/picker_style.ex
lib/live_view_native_swift_ui/modifiers/controls_and_indicators/progress_view_style.ex
lib/live_view_native_swift_ui/modifiers/controls_and_indicators/toggle_style.ex
lib/live_view_native_swift_ui/modifiers/layout_adjustments/layout_priority.ex
lib/live_view_native_swift_ui/modifiers/layout_adjustments/padding.ex
lib/live_view_native_swift_ui/modifiers/layout_adjustments/scene_padding.ex
lib/live_view_native_swift_ui/modifiers/layout_fundamentals/background.ex
lib/live_view_native_swift_ui/modifiers/layout_fundamentals/grid_cell_anchor.ex
lib/live_view_native_swift_ui/modifiers/layout_fundamentals/grid_cell_columns.ex
lib/live_view_native_swift_ui/modifiers/layout_fundamentals/grid_cell_unsized_axes.ex
lib/live_view_native_swift_ui/modifiers/layout_fundamentals/grid_column_alignment.ex
lib/live_view_native_swift_ui/modifiers/layout_fundamentals/overlay.ex

This adds modifier constructors such as the following:
```elixir
padding(:horizontal)
padding(16)
padding(:top, 16)
padding([top: 8, trailing: 10])
background({:color, :red})
background({:color, :red}, in: :capsule)
background(in: :capsule)
overlay({:color, :red})
overlay({:color, :red}, in: :capsule)
transition({:move, [edge: :bottom]})
button_style(:bordered_prominent)
progress_view_style(:linear)
```
This attempts to match SwiftUI modifier syntax as closely as possible. However, I'm not sure if its better to reflect this exactly in some cases, or to make something that is more natural in Elixir.
For example, in Swift it is encouraged to [use prepositions as argument labels](https://www.swift.org/documentation/api-design-guidelines/#argument-labels). However, I am not sure if this is …

Add more modifier constructors

---

README.md
Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/LiveView.swift
Sources/LiveViewNative/LiveViewHost.swift
Sources/LiveViewNative/LiveViewNative.docc/GettingStarted.md
Sources/LiveViewNative/LiveViewNative.docc/LiveViewNative.md
Sources/LiveViewNative/LiveViewNative.docc/Resources/01-02-06-session.swift
Sources/LiveViewNative/LiveViewNative.docc/Resources/01-02-07-liveview.swift
Sources/LiveViewNative/LiveViewNative.docc/Resources/03-02-01-navigationmode.swift
Sources/LiveViewNative/LiveViewNative.docc/Resources/04-01-04-session.swift
Sources/LiveViewNative/LiveViewNative.docc/Tutorials/01 Initial List.tutorial

Currently, to create a new LiveView Native project, users need to write code that uses `StateObject`, `LiveSessionCoordinator`, `LiveView`, `URL`, self-executing closures, and more. In some cases, this will be their first time using Swift, so code like this can seem confusing:
```swift
struct ContentView: View {
@StateObject private var coordinator = {
let config = LiveSessionConfiguration()
config.navigationMode = .enabled
return LiveSessionCoordinator(URL(string: "http://localhost:4000")!, config: config)
}
var body: some View {
LiveView(session: session)
}
}
```
This PR adds two new features to make this process simpler:
1. `LiveViewHost` protocol
2. `LiveSessionConfiguration` initializers
Using these two features, an equivalent setup looks like this:
```swift
struct ContentView: View …
```

Add simplified init for `LiveView`

---

Sources/LiveViewNative/Property Wrappers/Attribute.swift
Sources/LiveViewNative/ViewTree.swift

This adds caching to the `@Attribute` property wrapper. The value will only be decoded if it has changed.
I've also updated the `modifiers` attribute to be handled with `@Attribute`, so it can get the benefits of the caching. It is especially useful here, as JSON decoding is expensive.

Add backing storage and caching for `@Attribute`

---

lib/live_view_native_swift_ui/modifiers/images/image_scale.ex
lib/live_view_native_swift_ui/modifiers/layout_fundamentals/z_index.ex
lib/live_view_native_swift_ui/modifiers/view_configuration/opacity.ex

This fixes some argument names and formatting for currently implemented modifier constructors.
I also swapped `is_float` for `is_number` so that integer literals can be passed in.

Minor fixes for modifier constructors

---

Sources/LiveViewNative/LiveView.swift
Sources/LiveViewNativeMacros/LiveViewMacro.swift
Sources/LiveViewNativeMacros/LiveViewNativeMacros.swift
Tests/LiveViewNativeMacrosTests/LiveViewNativeMacrosTests.swift

This adds a `#LiveView` macro that simplifies `LiveView` creation with add-on registries in Swift 5.9+.
Addons can be provided in an array of metatypes. The aggregate registry will be automatically synthesized, and passed as a generic argument to the `LiveView`.
```swift
struct ContentView: View {
var body: some View {
#LiveView(
.localhost,
addons: [ChartsRegistry<_>.self, AVKitRegistry<_>.self]
)
}
}
```
Previously, an `AggregateRegistry` needed to be created manually:
```swift
struct ContentView: View {
var body: some View {
LiveView<MyRegistry>(.localhost)
}
}
enum MyRegistry: AggregateRegistry {
#Registries<
ChartsRegistry<Self>,
AVKitRegistry<Self>
>
}
```
This macro automatically expands to the following:
```swift
{ () -> AnyView in
enum …
```

Add `#LiveView` macro for registering add-on libraries

---

Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/NavStackEntryView.swift
Sources/LiveViewNative/Registries/CustomRegistry.swift
Sources/LiveViewNative/ViewModel.swift
Tests/RenderingTests/assertMatch.swift

This adds support for persisting native binding values with UserDefaults.
```elixir
defmodule PersistenceTestLive do
use Phoenix.LiveView
use LiveViewNative.LiveView
native_binding :count, :integer, default: 0, persist: :scoped
def mount(_params, _session, socket) do
{:ok, socket}
end
def render(%{ platform_id: :swiftui } = assigns) do
~SWIFTUI"""
<Text>Persistent Counter</Text>
<Button phx-click="increment"><%= @count %></Button>
"""
end
def render(assigns) do
~H"""
"""
end
end
```
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/6933c59e-ffb3-4524-80e9-a3527e304f8d

Persistent native bindings with UserDefaults

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/NavStackEntryView.swift
Sources/LiveViewNative/Property Wrappers/LiveBinding.swift
Sources/LiveViewNative/Registries/CustomRegistry.swift
Sources/LiveViewNative/ViewModel.swift
Tests/RenderingTests/assertMatch.swift

This changes the payload of `_native_bindings` from:
```json
{ ... }
```
to:
```json
{ "data": { ... }, "animation": animation or null }
```
Native bindings can also be debounced with:
```html
<SomeElement value-binding={:my_binding} value-binding:debounce={1} />
```

Support animation and debounce with native bindings

---

Package.resolved
Sources/LiveViewNative/BuiltinRegistry+applyBinding.swift
Sources/LiveViewNative/ViewTree.swift
Sources/LiveViewNative/Views/Controls and Indicators/Buttons/Button.swift
Sources/LiveViewNative/Views/Controls and Indicators/Buttons/PasteButton.swift
Sources/LiveViewNative/Views/Text Input and Output/SecureField.swift
Sources/LiveViewNative/Views/Text Input and Output/TextEditor.swift
Sources/LiveViewNative/Views/Text Input and Output/TextField.swift

Needed for some MapKit functionality, and potentially other add-on libraries. The type has been underscored to discourage use in user code and hide from auto-complete.

Make `ProvidedBindingsKey` public

---

Sources/LiveViewNative/Property Wrappers/LiveContext.swift
Sources/LiveViewNative/Utils/AnyTransition.swift
Sources/LiveViewNative/Utils/ContentTransition.swift
Sources/LiveViewNative/ViewTree.swift

This resolves an issue where elements would stick around when replaced with another element, which can lead to undefined behavior.
Using `ForEach` instead of `TupleView` gives each element an explicit identifier based on its `NodeRef`. My guess is that having the structural identity provided by `TupleView` caused elements to not be replaced properly when the parent container received an update.

Use `NodeRef` as element id with `ForEach` instead of `TupleView`

---

Sources/LiveViewNative/Property Wrappers/Attribute.swift
Sources/LiveViewNative/Property Wrappers/LiveContext.swift
Sources/LiveViewNative/Property Wrappers/ObservedElement.swift
Sources/LiveViewNative/ViewTree.swift

This includes two optimizations:
1. Removed extra wrapping Views, such as `NodeView`. This manual inlining reduced some View.body evaluations.
2. Add explicit `objectWillChange` properties to `ObservableObject` subclasses. Oddly, the slowest part of a View update was the default `objectWillChange` getter provided by the `ObservableObject` protocol. I'm not sure how they implemented this getter, but adding a simple implementation drastically improved update performance.
I tested these changes on a LiveView with around 200 elements and some moderately complex modifier stacks:
Previously, Instruments reported a microhang of ~400ms anytime an updated happened. The initial app load also took over 4 seconds.
After these optimizations, updates typically take <=100ms and the initial app loads in …

Optimize updates with ObservableObject

---

Package.resolved

Removes duplicate `swift-syntax` entry that broke the build.

Fix Package.resolved

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift

This allows a LiveView to be created with no web template.

Pass `_platform` as a query param on initial page load

---

Sources/LiveViewNative/Coordinators/LiveConnectionError.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/LiveView.swift

Closes #1015 
Closes #1014 
Events can now be received from the `LiveSessionCoordinator`. All `LiveViewCoordinator` events with matching names will be sent to the session coordinator. The `LiveViewCoordinator` is returned in the payload so the events can be distinguished, and replies can be sent.
`pushEvent` now supports sending an `Encodable` struct as well.
```swift
.onReceive(session.receiveEvent("my_custom_event")) { (coordinator, payload) in
Task {
try await coordinator.pushEvent(type: "click", event: "test_reply", value: EventData(reply1: 5, id: "hello, world!"))
}
}
```

Add `Encodable` to `pushEvent` and `receiveEvent` from `LiveSessionCoordinator`

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift

`disconnect` now waits for the channel to be left before returning.
This fixes some crashes related to `push_navigate` happening too quickly.

Wait for disconnect to finish

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift

This appears to fix the issue described in #1062 by ensuring the `onClose` handler is removed before resuming the continuation. I also fixed a continuation misuse that happened if the server was shutdown after the socket already connected by disabling the `onError` and `onOpen` handlers after one is called.

Disable onClose handler after receiving once

---

Sources/LiveViewNative/Views/Text Input and Output/TextField.swift

The docs are using the incorrect key for the `keyboard_type` modifier.

Use correct key for keyboard_type modifier in TextField docs

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/Navigation/LiveRedirect.swift

Closes #1109 
Previously, `live_redirect` was only handled in response to events. However, when `handle_info` results in a `push_navigate` a `live_redirect` message is sent independent of an event. This adds a handler for this message on all channels.

Handle `live_redirect` outside of events

---

Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift

When implementing this initially, I assumed that a join event would only be sent once. However, it seems this is better represented by an `AsyncStream`.
This fixes some issues with reconnection. When the server crashes or the app is backgrounded, the channel receives another join message. Previously, this would crash the client. With these changes, the `LiveViewCoordinator` should be able to handle subsequent joins more gracefully.

Use `AsyncThrowingStream` to handle join replies

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/LiveView.swift

This resolves the following issues:
* Incorrect back button titles on the second page
* Second page is shown when navigating back, until the first page loads

Fix navigation root URL state

---

README.md

Removing outdated tutorial link from README

Removing outdated tutorial link

---

Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift
Sources/LiveViewNative/NavStackEntryView.swift

This adds a configuration option that lets you add a transition between the progress indicator and the loaded page.
Simply add the `transition` argument to your `LiveSessionConfiguration`:
```swift
LiveView(.localhost, configuration: .init(transition: .opacity))
```
Here's a before/after sample using the `opacity` transition:
| Before | After |
| --- | --- |
| <video src="https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/28947706-9dca-4632-bee4-d0c97bc22406" /> | <video src="https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/75bfe372-ed07-4595-927c-803516344cff" /> |
Page loads are much less jarring with these changes. You can use any type of transition in your configuration, such as `.scale` or `.move(edge: .bottom)`: …

Add transition configuration for page loads

---

lib/live_view_native/swiftui/rules_helpers.ex
lib/live_view_native/swiftui/rules_parser.ex
test/live_view_native/swiftui/rules_helpers_test.exs

to_ime
This also added __using__/1 to LiveViewNative.RulesParser so we can import the rules helpers into the Sheet
The `to_ime` is half-baked. There will need to be more complex edge cases accounted for here like chaining and function calls.

Add SwiftUI specific rules helpers

---

Package.resolved
Sources/LiveViewNative/Modifiers/Menus and Commands/MenuActionDismissBehaviorModifier.swift
Sources/LiveViewNative/Modifiers/Menus and Commands/MenuOrderModifier.swift
Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationBackgroundInteractionModifier.swift
Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationBackgroundModifier.swift
Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationCompactAdaptationModifier.swift
Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationContentInteractionModifier.swift
Sources/LiveViewNative/Modifiers/Modal Presentations/PresentationCornerRadiusModifier.swift
Sources/LiveViewNative/Modifiers/Scroll Views Modifiers/ScrollBounceBehaviorModifier.swift
Sources/LiveViewNative/Modifiers/Search Modifiers/SearchScopesModifier.swift
Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/MonospacedModifier.swift
Sources/LiveViewNative/Modifiers/View Groupings Modifiers/ControlGroupStyleModifier.swift
Sources/LiveViewNative/Utils/ContentTransition.swift
Sources/LiveViewNative/Utils/ScrollBounceBehavior.swift
Sources/LiveViewNative/Views/Text Input and Output/Text.swift

This supports building the package with Swift 5.7 (distributed with Xcode 14.2).
Closes #1005

Support building with Swift 5.7

---

Package.swift
Package@swift-5.9.swift

Closes #1136 
Some flags were being passed to the compiler to improve our generated documentation output.
However, these flags were causing issues in newer versions of Xcode when using a version number instead of a branch name or commit hash.
The flags have been removed. If we decide to continue using DocC for documentation instead of switching to hexdocs, we may need to find a workaround for this. A few options are:
1. Move the documentation on affected extensions into articles
2. Conditionally add these "unsafe" flags when building documentation
3. See if newer/upcoming versions of Swift emit this documentation by default and use those for building documentation
I think one of these options could be implemented in a separate PR.

Remove `swiftSettings` arguments for documentation

---

lib/live_view_native/swiftui/rules_parser.ex
lib/live_view_native/swiftui/rules_parser/expressions.ex
lib/live_view_native/swiftui/rules_parser/modifiers.ex
lib/live_view_native/swiftui/rules_parser/parser.ex
lib/live_view_native/swiftui/rules_parser/parser/error.ex
lib/live_view_native/swiftui/rules_parser/tokens.ex
test/live_view_native/swiftui/rules_parser_test.exs

- Fix parsing of `foo(x: to_integer(value), y: 0)`.
- Improve related error handling

Fix key/value pairs with helper calls

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/LiveView.swift
Sources/LiveViewNative/NavStackEntryView.swift
Tests/RenderingTests/assertMatch.swift

Closes #1130
- ~~Provide the same functionality for `push_patch`~~ - `push_patch` is functional, but will instead show the current page due to the shared channel.
This persists the `Document` for disconnected pages, and ensures there is one `LiveViewCoordinator` per navigation history entry.
Previously, navigating backward would temporarily show a blank page:
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/08d829cd-16d2-4719-a251-970b7fbcb043
With these changes, there is now a disabled version of the page still visible, which is then replaced with the newly rendered page after it reconnects:
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/e4a25717-3692-4b54-a82d-b09527ca0c65

Continue rendering disconnected pages in navigation path

---

Sources/LiveViewNative/Property Wrappers/FormState.swift
Sources/LiveViewNative/ViewModel.swift

Closes #1141 by storing its initial value to the `formModel` when the `@FormState` wrapper is setting up.

Set default value for FormModel

---

.github/ISSUE_TEMPLATE/bug-report---swift.yml

The issue template had incorrect instructions on locating the Swift version.
The easiest way to find the Swift version is by running:
```
swift --version
```

Update Swift version instructions

---

lib/live_view_native/swiftui/rules_parser/expressions.ex
lib/live_view_native/swiftui/rules_parser/modifiers.ex
lib/live_view_native/swiftui/rules_parser/post_processors.ex
lib/live_view_native/swiftui/rules_parser/tokens.ex
test/live_view_native/swiftui/rules_parser_test.exs

@bcardarella, this PR supports `foo(Foo.bar...Baz.qux)` but not deeply nested members eg `foo(Foo.bar.baz...Baz.qux)`.
Let me know if we also need support for the latter.

Add Swift range support

---

Sources/LiveViewNativeStylesheetMacros/ParseableExpressionMacro.swift
Tests/LiveViewNativeStylesheetMacrosTests/MacroTests.swift

`@ParseableExpression` previously skipped `#if` wrapped `inits`, but will now propagate the condition throughout its generated parsing code.

Fix `@ParseableExpression` macro for `#if` wrapped `init`s

---

Sources/LiveViewNative/Stylesheets/ViewReference.swift
Sources/LiveViewNativeStylesheet/Parsing/Literals/ListLiteral.swift

Closes #1173 
Previously, strings were accepted for references. Now, only atoms and lists of atoms are allowed.
```elixir
background(content: "my_content")
background(content: :my_content)
```

Only allow atoms for View/Text/Toolbar references

---

Sources/LiveViewNative/Stylesheets/Modifiers/Overrides/MatchedGeometryEffectModifier.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/Animation+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/AnySymbolEffect.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/Color+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/SymbolVariants+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/UnitCurve+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/StylesheetParser.swift
Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/LiveViewNativeStylesheet/Parsing/Literals/ListLiteral.swift
Sources/LiveViewNativeStylesheet/Parsing/Literals/NilLiteral.swift
Sources/ModifierGenerator/ModifierGenerator.swift
Sources/ModifierGenerator/Signature.swift

This fixes a bug where generated `AttributeReference` types would have their default values removed.
It also includes fixes for the parsers of a few modifiers and types.

Fix modifier default values and missing initializers

---

.gitignore
CHANGELOG.md
README.md
Sources/LiveViewNative/LiveViewNative.docc/LiveViewNative.md
Sources/LiveViewNative/LiveViewNative.docc/Resources/01-01-03-mix.exs
Sources/LiveViewNative/LiveViewNative.docc/Tutorials/01 Initial List.tutorial
lib/live_view_native/swiftui/platform.ex
lib/mix/tasks/install.ex
mix.exs
util/encode_modifiers.exs

Our naming convention is `swiftui`

Rename swift_ui to swiftui

---

lib/live_view_native/swiftui/rules_parser/parser/annotations.ex
lib/live_view_native/swiftui/rules_parser/parser/context.ex
test/live_view_native/swiftui/rules_parser_test.exs

Resolves https://github.com/liveview-native/live_view_native_stylesheet/issues/31

Include original source in the annotation

---

Sources/LiveViewNative/Coordinators/LiveSessionState.swift
Sources/LiveViewNative/NavStackEntryView.swift
Sources/LiveViewNative/Views/Navigation/NavigationStack.swift

This improves the cached page rendering when using `<NavigationStack>` in a layout.
Previously, the page would go blank during transitions. With these changes, the previous page will display with the `disabled` modifier applied until is focused. Here's a demo with animations slowed:
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/782db1d3-6db4-424a-9ebc-be2c1e489f84

Fix cached page rendering when nested in `<NavigationStack>`

---

Sources/LiveViewNativeMacros/LiveViewMacro.swift
Sources/LiveViewNativeMacros/RegistriesMacro.swift

Some things were renamed in newer Xcode betas.

Update macros for swift-syntax deprecations

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift

Closes #1206 
Previously, the old document was left when disconnecting from the socket. This caused the diffing to break on live reload when the new document was sent.

Remove documents when disconnecting socket

---

Package.swift
Sources/LiveViewNative/ContentBuilder.swift
Sources/LiveViewNative/Property Wrappers/ChangeTracked.swift
Sources/LiveViewNative/Registries/AggregateRegistry.swift
Sources/LiveViewNative/Registries/CustomRegistry.swift
Sources/LiveViewNative/Stylesheets/AttributeReference.swift
Sources/LiveViewNative/Stylesheets/Stylesheet.swift
Sources/LiveViewNative/Stylesheets/StylesheetParser.swift
Sources/LiveViewNative/Stylesheets/ViewReference.swift
Sources/LiveViewNative/ViewModifierBuilder.swift
Sources/LiveViewNative/ViewTree.swift
Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/LiveViewNativeMacros/LiveViewMacro.swift
Sources/LiveViewNativeStylesheet/ModifierParseError.swift
Sources/LiveViewNativeStylesheet/Parsing/External/ParseableModifier.swift
Sources/ModifierGenerator/ModifierGenerator.swift

This PR deals with modifiers in multiple contexts which I'll refer to as:
* "root context" - the main app, uses SwiftUI Views
* "content builder context" - custom element types in a specific View. For example, `MapContent` or `ChartContent` instead of View types.
Changes:
* `AggregateRegistry` now properly collects modifiers from addons. This also fixes the `#LiveView(_:addons:)` macro, which used `AggregateRegistry` internally.
* Custom modifiers from the registry will now be parsed after built-in modifiers (were previously ignored).
* `ContentBuilder` can declare custom modifiers and use classes on its elements. These should also be included in the `CustomRegistry` for the add-on to avoid parsing errors.
* `LiveViewNativeStylesheet` was made available to external packages for use in …

Support custom modifiers from registries and in `ContentBuilder`

---

Package.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/Alignment+ParseableModifierValue.swift
Tests/LiveViewNativeStylesheetTests/LiveViewNativeStylesheetTests.swift

The ordering of the alignment cases caused parsing to fail for some compound cases, such as `topLeading`.
I have added a test for this type as well.

Re-order `Alignment` cases

---

Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/ModifierGenerator/ModifierGenerator.swift
Sources/ModifierGenerator/Schema.swift

This adds a `--schema` flag to the modifier generator. This changes the output to a JSON format that is read by the LiveView Native VS Code extension to provide code completion.
See https://github.com/liveview-native/liveview-native-vscode/pull/5 for an example output and use-case.

Add `--schema` flag to `ModifierGenerator`

---

Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/LiveViewNativeStylesheet/ModifierParseError.swift
Sources/ModifierGenerator/ModifierGenerator.swift
Sources/ModifierGenerator/ModifierVisitor.swift

Closes #1219 
The modifier generator can now extract deprecation messages from modifiers. If a modifier fails to parse, and it has a known deprecation, it will be reported as a `deprecatedModifier` error. Otherwise, it is an `unknownModifier` error.
```
Stylesheet parsing failed for modifier `foregroundColor` in class `navigation-title`:
|
36 | foregroundColor(.red)
| ^ `foregroundColor` is deprecated: renamed to `foregroundStyle(_:)`
in ElixirconfChessWeb.Styles.AppStyles (app_styles.ex:36)
```
This applies to all deprecated modifiers, not just `foregroundColor`.

Add deprecation notices to modifier error handling

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift

The `_format` parameter is needed for v0.3.0

Pass `_format` to channel

---

lib/live_view_native/swiftui/rules_parser.ex
lib/live_view_native/swiftui/rules_parser/modifiers.ex
lib/live_view_native/swiftui/rules_parser/post_processors.ex
test/live_view_native/swiftui/rules_parser_test.exs

Support `Color(...).opacity(0.25)` in
```swift
foregroundStyle(Color(.displayP3, red: 0.4627, green: 0.8392, blue: 1.0).opacity(0.25))
```
Resolves https://github.com/liveview-native/live_view_native_stylesheet/issues/41

Support ime's chained to modifiers

---

Sources/LiveViewNative/FormValue.swift
Sources/LiveViewNative/Property Wrappers/Attribute.swift
Sources/LiveViewNative/Property Wrappers/ChangeTracked.swift
Sources/LiveViewNative/Property Wrappers/FormState.swift
Sources/LiveViewNative/Stylesheets/Stylesheet.swift
Sources/LiveViewNative/Utils/Alignment.swift
Sources/LiveViewNative/Utils/Angle.swift
Sources/LiveViewNative/Utils/Axis.swift
Sources/LiveViewNative/Utils/ColorScheme.swift
Sources/LiveViewNative/Utils/DOM.swift
Sources/LiveViewNative/Utils/Font.swift
Sources/LiveViewNative/Utils/PinnedScrollableViews.swift
Sources/LiveViewNative/Utils/Selection.swift
Sources/LiveViewNative/Utils/UnitPoint.swift
Sources/LiveViewNative/Utils/Visibility.swift
Sources/LiveViewNative/Views/Controls and Indicators/Pickers/ColorPicker.swift
Sources/LiveViewNative/Views/Controls and Indicators/Pickers/DatePicker.swift
Sources/LiveViewNative/Views/Drawing and Graphics/ColorView.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Table.swift
Sources/LiveViewNative/Views/Shapes/Shape.swift
Sources/LiveViewNative/Views/Text Input and Output/Text.swift
Sources/LiveViewNative/Views/Toolbars/ToolbarItem.swift
Sources/LiveViewNative/Views/Toolbars/ToolbarItemGroup.swift

This adds the `ElementNode` as an argument to the `AttributeDecodable` initializer. This allows attributes to look up the value of other attributes.

Refactor AttributeDecodable API

---

Sources/LiveViewNative/ContentBuilder.swift
Sources/LiveViewNative/Stylesheets/StylesheetParser.swift
Sources/LiveViewNativeStylesheet/ModifierParseError.swift
Sources/LiveViewNativeStylesheet/Parsing/External/AnyNodeParser.swift
Sources/LiveViewNativeStylesheetMacros/ParseableExpressionMacro.swift

Previously, error messages would only mention which modifier failed and provide a list of possible clauses.
The new error messages have details on which arguments failed, with possible solutions for fixing more complex types (such as `ViewReference` and `ChangeTracked`):
```
Stylesheet parsing failed for modifier `sheet` in class `sheet`:
|
6 | sheet(isPresented: "isPresented", onDismiss: event("onDismiss"), content: "content")
| ^ Clause `sheet(isPresented:onDismiss:content:)` failed:
|     - Incorrect value passed to argument `isPresented`. Expected `ChangeTracked<Bool>` but got `"isPresented"`. Use `attr("...")` to link this argument with an attribute.
|     - Incorrect value passed to argument `content`. Expected `ViewReference` but got `"content"`. Pass an atom type to reference …
```

Add argument type mismatch error message

---

Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/ModifierGenerator/ModifierGenerator.swift
Sources/ModifierGenerator/Signature.swift

Closes #1245 
This was related to a similar issue #806.
To resolve this, a new `chunk-size` option was added to the modifier generator. This will split the builtin modifier enum into chunks, which the main `BuiltinModifier` type defers to.

Chunk modifiers to reduce stack size

---

Sources/LiveViewNative/Utils/Selection.swift

Closes #1213 
Pass a JSON encoded array to allow for multi-select. This also works with the `EditButton` element.
```ex
def mount(_params, _session, socket) do
{:ok, assign(socket, selection: [])}
end
def render(%{format: :swiftui} = assigns) do
~SWIFTUI"""
<EditButton />
<List selection={Jason.encode!(@selection)} phx-change="selection-changed">
<Text id={"#{i}"} :for={i <- 1..10}><%= i %></Text>
</List>
"""
end
def handle_event("selection-changed", %{ "selection" => selection }, socket) do
{:noreply, assign(socket, selection: selection)}
end
```
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/c9ac86fc-a8d9-43c3-bb2f-af951620482e

Support multi-item selection

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveSessionState.swift
Sources/LiveViewNative/ErrorModifier.swift
Sources/LiveViewNative/ErrorView.swift
Sources/LiveViewNative/LiveErrorView.swift
Sources/LiveViewNative/LiveView.swift
Sources/LiveViewNative/LiveViewHost.swift
Sources/LiveViewNative/NavStackEntryView.swift
Sources/LiveViewNative/Registries/AggregateRegistry.swift
Sources/LiveViewNative/Registries/CustomRegistry.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/ShapeStyles/AnyShapeStyle+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ViewReference.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Table.swift
Sources/LiveViewNativeMacros/LiveViewMacro.swift
priv/xcodegen/Sources/TemplateApp/ContentView.swift

Closes #1232 
State views can be provided as arguments to the `LiveView`. The `loadingView` method was from the `CustomRegistry` protocol, as it makes more sense to provide these options on the `LiveView` itself. Here's an example of using these arguments:
```swift
LiveView(.localhost) {
ProgressView("Loading")
} disconnected: {
Text("Not connected to the server")
} reconnecting: { content in
content
.safeAreaInset(edge: .bottom) {
HStack {
ProgressView()
Text("Reconnecting")
}
.padding()
.frame(maxWidth: .infinity, alignment: .leading)
.background(Color.orange)
}
} error: { error in
Text(error.localizedDescription)
}
```
Note that `reconnecting` provides the `content` of the `LiveView`, allowing you to create an overlay instead of fully replacing the screen when the connection …

Customizable `LiveView` state views

---

priv/xcodegen/Sources/TemplateApp/ContentView.swift
priv/xcodegen/Sources/TemplateApp/DisconnectedView.swift
priv/xcodegen/Sources/TemplateApp/ErrorView.swift
priv/xcodegen/Sources/TemplateApp/ReconnectingView.swift
priv/xcodegen/base_spec.yml

The state views are extracted into their own views to make the ContentView less cluttered and to provide a clean location to make changes. This also allows Previews to be used.
Also suppress the recommended changes warnings when generating a new project

Extract state views into their own views and address warnings

---

Sources/LiveViewNative/Property Wrappers/Attribute.swift
Sources/LiveViewNative/Property Wrappers/ObservedElement.swift
Sources/LiveViewNative/Views/Images/ImageView.swift

Avoid accessing `StateObject` or `Environment` when in a nested View context

---

Sources/LiveViewNative/Views/Controls and Indicators/Links/Link.swift
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/NavigationLink.swift

Closes #1256 
If the URL is invalid, the content of the View will be rendered instead.

Safely unwrap `NavigationLink` and `Link` URLs

---

priv/xcodegen/Sources/TemplateApp/ErrorView.swift

The Copy Error button used `UIPasteboard`, which is not available on macOS.

Add `NSPasteboard` to Copy Error button

---

Sources/LiveViewNative/Utils/Selection.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/List.swift

Previously, if the `selection` value was `nil` to start (the attribute is missing), List selection was disabled.
With this PR, when the `selection` attribute is `nil` but the `phx-change` attribute is present, it will allow selection.

Allow list selection when default is `nil` but `phx-change` is present

---

Sources/LiveViewNative/Views/Accessibility/ScaledMetric.swift
Sources/LiveViewNative/Views/Controls and Indicators/Pickers/Picker.swift
Sources/LiveViewNative/Views/Controls and Indicators/Value Inputs/Toggle.swift
Sources/LiveViewNative/Views/Images/ImageView.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Table.swift
Sources/LiveViewNative/Views/Layout Containers/Groups/DisclosureGroup.swift
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/HSplitView.swift
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/TabView.swift
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/VSplitView.swift
Sources/LiveViewNative/Views/Layout Containers/Scroll Views/ScrollView.swift
Sources/LiveViewNative/Views/Text Input and Output/Text.swift
Sources/LiveViewNative/Views/Text Input and Output/TextField.swift
Sources/LiveViewNative/Views/Toolbars/ToolbarItem.swift
Sources/LiveViewNative/Views/Toolbars/ToolbarItemGroup.swift
Tests/RenderingTests/TextTests.swift

Some property values were missed in #1257. This also updates any documentation that was still using `kebab-case` attributes.

Convert missed attributes to camel case

---

Sources/LiveViewNative/ContentBuilder.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/BaselineOffsetModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/BoldModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/FontDesignModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/FontModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/FontWeightModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/FontWidthModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/ForegroundStyleModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/ItalicModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/KerningModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/MonospacedDigitModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/MonospacedModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/StrikethroughModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/TextModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/TextScaleModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/TrackingModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/UnderlineModifier.swift
Sources/LiveViewNative/Stylesheets/ViewReference.swift
Sources/LiveViewNative/ViewTree.swift
Sources/LiveViewNative/Views/Accessibility/ScaledMetric.swift
Sources/LiveViewNative/Views/Controls and Indicators/Links/Link.swift
Sources/LiveViewNative/Views/Images/ImageView.swift
Sources/LiveViewNative/Views/Layout Containers/Groups/Group.swift
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/TabView.swift
Sources/LiveViewNative/Views/Layout Containers/Scroll Views/ScrollView.swift
Sources/LiveViewNative/Views/Text Input and Output/Text.swift
Sources/LiveViewNative/Views/Text Input and Output/TextField.swift
Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/ModifierGenerator/ModifierGenerator.swift

Nested `Text` elements will now receive modifiers.
Some documentation was still using `modifiers={...}`.
This updates those docs to use classes instead.

Allow classes on nested `Text`, and update docs

---

Sources/LiveViewNative/Utils/ButtonRole.swift
Sources/LiveViewNative/Views/Controls and Indicators/Buttons/Button.swift

Closes #1278 
This adds support for the `role` attribute on `Button`.
It also removes the `disabled` attribute, which should be applied with a modifier.
```heex
<Button role="destructive">
<Label systemImage="arrow.uturn.backward">Undo Send</Label>
</Button>
```

Add `role` attribute to `Button` and remove `disabled`

---

Sources/LiveViewNative/Views/Text Input and Output/Text.swift

Closes #1281 
This adds the `content` attribute for `Text`, but continues to recommend using child elements in the documentation.

Add `content` attribute for `Text`, but recommend using children

---

Sources/LiveViewNative/Utils/Alignment.swift
Sources/LiveViewNative/Views/Toolbars/ToolbarItem.swift

Closes #1290 
Closes #1291 
Here's an example of the `bottomBar` placement being used:
```heex
<ToolbarItem template="toolbar" placement="bottomBar">
<HStack>
<Button><Image systemName="line.3.horizontal.decrease.circle" /></Button>
<Spacer />
<Button><Image systemName="square.and.pencil" /></Button>
</HStack>
</ToolbarItem>
```

Add missing `HorizontalAlignment`, `VerticalAlignment`, and `ToolbarItemPlacement` cases

---

Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/NavStackEntryView.swift
Sources/LiveViewNative/Property Wrappers/Attribute.swift
Sources/LiveViewNative/Property Wrappers/FormState.swift
Sources/LiveViewNative/Utils/DOM.swift
Sources/LiveViewNative/ViewModel.swift
Sources/LiveViewNative/Views/Images/AsyncImage.swift

Related to https://github.com/liveview-native/liveview-native-live-form/pull/9
* Support code for sending a request to `action` attribute of a `LiveForm`
* Reconnects can be performed with a `POST`, or any other http method
* *Breaking change*: `urlSession` configuration option was changed to a `urlSessionConfiguration` option. This allows the `LiveSessionCoordinator` to manage the session.
* `LiveSessionCoordinator` automatically adds `_format=swiftui` to any redirects.

Updates for LiveForm and web parity

---

Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/Property Wrappers/LiveContext.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Images/ImageModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Images/RenderingModeModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Images/ResizableModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/BaselineOffsetModifier.swift
Sources/LiveViewNative/ViewTree.swift
Sources/LiveViewNative/Views/Controls and Indicators/Links/ShareLink.swift
Sources/LiveViewNative/Views/Images/AsyncImage.swift
Sources/LiveViewNative/Views/Images/ImageView.swift
Sources/LiveViewNative/Views/Text Input and Output/Text.swift
Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/ModifierGenerator/ModifierGenerator.swift

Closes #1243
Current API:
```html
<AsyncImage url="...">
<Group template="phase.empty">
<ProgressView />
</Group>
<Group template="phase.success">
<AsyncImage image class="resizable" /> 
</Group>
<Group template="phase.failure">
<AsyncImage error /> 
</Group>
</AsyncImage>
```

ViewBuilder closure argument support

---

Sources/LiveViewNativeStylesheetMacros/ParseableExpressionMacro.swift
Tests/LiveViewNativeStylesheetTests/ShapeStyleTests.swift

Closes #1304 
Previously, it expected a comma to start the keyword arguments.
```ex
[:sRGB, [red: 1, green: 1, blue: 1]]
```
However, if the unlabeled argument `:sRGB` is not provided and the default value is used, the comma would not be present and parsing would fail.
Now, it looks for a comma *or* an open bracket `[`. This properly handles the case where all default values are used for the unlabeled arguments.
```ex
[[red: 1, green: 1, blue: 1]]
#^ bracket starts keyword args
```

Properly handle default arguments to `@ParseableExpression`s

---

Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/TabView.swift

Closes #1305 
This will allow `TabView` to be used without specifying a `tag` on each child element, or handling the page changes with `phx-change` and `selection`.

Only pass `$selection` binding if attributes are present

---

Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Live/LiveErrorView.swift
Sources/LiveViewNative/Live/LiveView.swift
Sources/LiveViewNative/Live/ReconnectLiveViewAction.swift
priv/templates/lvn.swiftui.gen/xcodegen/TemplateApp/ErrorView.swift

Closes #1310
This adds a reconnect button to the `LiveErrorView`. It provides options to reconnect on the current route or from the root.
A new API was also added so users can trigger a reconnect without needing access to the session.
This follows the design of actions like [`openWindow`](https://developer.apple.com/documentation/swiftui/environmentvalues/openwindow) and [`dismiss`](https://developer.apple.com/documentation/swiftui/environmentvalues/dismiss) in SwiftUI.
```swift
struct MyCustomView: View {
@Environment(\.reconnectLiveView) private var reconnectLiveView
var body: some View {
Button("Reconnect") {
Task {
await reconnectLiveView()
await reconnectLiveView(.restart) // use the `restart` style to reconnect from the base URL.
}
}
}
}
``` …

Add reconnect menu to `LiveErrorView`

---

Sources/LiveViewNative/Live/LiveView.swift
Sources/LiveViewNative/Registries/CustomRegistry.swift
Sources/LiveViewNativeMacros/AddonMacro.swift
Sources/LiveViewNativeMacros/LiveViewMacro.swift
Sources/LiveViewNativeMacros/LiveViewNativeMacros.swift

Closes #1296 
Previously, addons were passed by type:
```swift
#LiveView(
.localhost,
addons: [ChartsRegistry<_>.self, LiveFormRegistry<_>.self]
)
```
This adds a new format for passing addons using static members on an `Addons` type:
```swift
#LiveView(
.localhost,
addons: [.charts, .liveForm]
)
```
This is simpler to read and write, and also allows for some helpful auto completion:
To make this work, the API for addon libraries has changed a bit.
Now, they should be declared as extensions on the `Addons` type. Add the `@Addon` macro on the struct.
```swift
public extension Addons {
@Addon
struct Charts<Root: RootRegistry> {
// ...
}
}
```
The `@Addon` macro will synthesize a static member by converting the type name to `camelCase`:
```swift
addons: [.charts]
```
The previous method of …

`@Addon` macro API

---

Package.resolved
Package.swift
Sources/LiveViewNative/Live/LiveErrorView.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Overrides/PerspectiveRotationEffectModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/FontDesignModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/TextScaleModifier.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/AffineTransform3D+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/DepthAlignment+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/EdgeInsets3D+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/ListSectionSpacing+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/OrnamentAttachmentAnchor+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/ShapeStyles/AnyShapeStyle+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/SurroundingsEffect+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/UITextContentType+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/UnitPoint3D.swift
Sources/LiveViewNative/Views/Controls and Indicators/Menus/Menu.swift
Sources/LiveViewNative/Views/Drawing and Graphics/NamespaceContext.swift
Sources/LiveViewNative/Views/Toolbars/ToolbarItem.swift
Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/LiveViewNative/visionOS+defaultWheelPickerItemHeight.swift
Sources/ModifierGenerator/ModifierGenerator.swift
Sources/ModifierGenerator/Subcommands/Source.swift
Sources/ModifierGenerator/Visitors/ModifierVisitor.swift

This updates the core dependency, with visionOS support included.
The `_GeneratedModifier.swift` was regenerated using Xcode 15.3, and uses the `arm64-apple-xros.swiftinterface` instead of the iOS file to include some missing modifiers. I also added missing types for these modifiers.

Add support for visionOS and missing modifiers/types

---

priv/templates/lvn.gen.layout/app.neex
priv/templates/lvn.swiftui.gen/core_components.ex

This adds the following core components:
* `modal`
* `flash`
* `flash_group`
* `list`
Updates were made to the following components:
* `button`
* `table`
A new `app.swiftui.neex` layout was added as well, which injects the `flash_group` component to support `put_flash` in all template projects.
<table>
<tr>
<th>Component</th>
<th>Demo</th>
</tr>
<tr>
<td>
```heex
<.flash_group flash={@flash} />
```
```ex
def handle_event("flash", _params, socket) do
{:noreply, put_flash(socket, :info, "This is an info flash")}
end
def handle_event("flash-err", _params, socket) do
{:noreply, put_flash(socket, :error, "This is an error flash")}
end
```
</td>
<td>
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/5e496735-97c1-4b34-afe6-b4981c168e11
</td>
</tr>
<tr>
<td>
```heex …
```

Add additional core components and app layout

---

Sources/LiveViewNative/Views/Controls and Indicators/Pickers/DatePicker.swift

Rename DatePicker's `components` to `displayedComponents`

---

Sources/LiveViewNative/JSONDecoder.swift
Sources/LiveViewNative/Utils/Transaction.swift
Sources/LiveViewNative/Utils/UnitPoint.swift
Sources/LiveViewNative/Views/Images/AsyncImage.swift

This removes the default animation from `AsyncImage`, and allows the user to provide a customize it instead.
```heex
<AsyncImage transaction={%{ animation: :default }} />
<AsyncImage transaction={%{ animation: :easeInOut }} />
<AsyncImage transaction={%{ animation: %{ linear: %{ duration: 4 } } }} />
```
The specified animation is used when the image transitions between phases.

Add `transaction` attribute to `AsyncImage`

---

Sources/LiveViewNative/Property Wrappers/FormState.swift
Sources/LiveViewNative/ViewModel.swift
Tests/RenderingTests/PickerTests.swift

Now, any element that uses `@FormState` won't send `phx-change` events unless it is nested within a `<LiveForm>`. It can be interacted with, but the entered values will not be persisted when outside of a form.
```heex
<TextField phx-change="changed">Name</TextField>
```
This will log a warning as well:
```
Form element used outside of a <LiveForm>. This may not behave as expected.
```
When inside a `LiveForm`, change events will be sent as normal:
```heex
<LiveForm id="test">
<TextField name="text-field" phx-change="changed">Name</TextField>
</LiveForm>
```
```
[debug] HANDLE EVENT "changed" in HelloWorldWeb.HomeLive
Parameters: %{"text-field" => "Testing"}
```
Related PR: https://github.com/liveview-native/liveview-native-live-form/pull/14

Disable change tracked `local` form state mode

---

Sources/LiveViewNative/Property Wrappers/ChangeTracked.swift
Sources/LiveViewNative/Property Wrappers/Event.swift
Sources/LiveViewNative/Property Wrappers/FormState.swift
Sources/LiveViewNative/ViewModel.swift
Sources/LiveViewNative/Views/Text Input and Output/SecureField.swift
Sources/LiveViewNative/Views/Text Input and Output/TextEditor.swift
Sources/LiveViewNative/Views/Text Input and Output/TextField.swift

Closes #1322 
`phx-debounce="blur"` only works on `<TextField>`, `<SecureField>`, and `<TextEditor>`. Other controls (like `<Slider>` or `<Toggle>`) don't seem capable of receiving focus. However, it could easily be expanded to other form controls as needed.
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/b6415b76-88c9-46ab-9bd4-66ff35ef615e

Support `phx-debounce="blur"`

---

Sources/LiveViewNative/Live/LiveElement.swift
Sources/LiveViewNative/LiveViewNative.docc/AddCustomElement.md
Sources/LiveViewNative/LiveViewNative.docc/AddCustomModifier.md

This updates the documentation pages on creating custom elements and modifiers for the latest API changes.
You can view this documentation from Xcode by pressing *Product -> Build Documentation*. This will build all LiveView Native documentation and open it in *Window -> Developer Documentation* once it completes. The pages are called "Adding Custom Elements" and "Adding Custom Modifiers".

Update addon documentation

---

Package.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift

This version fixes a few memory leaks that were impacting LiveView Native.

Update SwiftPhoenixClient to 5.3.2

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveSessionState.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/Live/LiveView.swift
Sources/LiveViewNative/NavStackEntryView.swift

Closes #1355 
This replaces the `notConnected` state with 2 new states:
* `setup` - the initial state when a coordinator has not attempted to connect yet
* `disconnected` - any other disconnected state after a connection has been established/attempted
`setup` maps to `LiveViewPhase.connecting` in the public API.

Add separate `setup` and `disconnected` states

---

Sources/ModifierGenerator/Subcommands/DocumentationExtensions.swift
Sources/ModifierGenerator/Subcommands/List.swift
Sources/ModifierGenerator/Subcommands/Schema.swift
lib/mix/tasks/lvn.swiftui.gen.docs.ex

This will automatically switch between using double `"` and single `'` quotes depending on the contents of the modifier being documented.
I've also updated the generator to use the XROS swiftinterface file instead of the iPhoneOS one to include visionOS modifiers in the generated documentation.

Use `style` attribute for generated docs

---

Sources/LiveViewNative/Utils/DOM.swift

This updates the check for boolean attributes so the following cases work:
```heex
<Element isOn />
<Element isOn="true" />
<Element isOn={true} />
<Element isOn="123" />
<Element isOn="any value" />
<Element />
<Element isOn="false" />
<Element isOn={false} />
```

Treat boolean attributes as true if present and != "false"

---

priv/templates/lvn.swiftui.gen/core_components.ex

This replaces the use of utility classes with inline styles in the generate `core_components.swiftui.ex` file.
All components should behave the same.

Update core components to use `style` attribute

---

Sources/LiveViewNative/Protocols/ContentBuilder.swift
Sources/LiveViewNative/Utils/DOM.swift

This opens up the `ElementNode` API for addon libraries.
They can now access the `Node` from an `ElementNode` instance. I've also added an `Identifiable` conformance to `ElementNode`, where the ID of the element node is the `node.id`

Expose `node` and `data` on ElementNode

---

Sources/LiveViewNative/Stylesheets/Modifiers/Overrides/FocusScopeModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Overrides/MaskModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Overrides/MatchedGeometryEffectModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Overrides/PrefersDefaultFocusModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Overrides/Rotation3DEffectModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Overrides/SearchCompletionModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Overrides/SearchScopesModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Shapes/ScaleModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Shapes/StrokeModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/BaselineOffsetModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/BoldModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/ItalicModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/KerningModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/MonospacedModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/StrikethroughModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/TextScaleModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/TrackingModifier.swift
Sources/LiveViewNative/Stylesheets/Modifiers/Text/UnderlineModifier.swift
Sources/ModifierGenerator/Subcommands/DocumentationExtensions.swift

Closes #1364 
Along with #1366, this PR switches the manually written documentation for modifiers to use the `style` attribute instead of a separate stylesheet.
It also removes the `<%!-- template --%>` and `# LiveView` comments from codeblocks as they are no longer needed for clarity.

Remove <%!-- template --%> specifier

---

Sources/LiveViewNative/Property Wrappers/ObservedElement.swift
Sources/LiveViewNative/Protocols/ContentBuilder.swift

This updates `ObservedElement.projectedValue` to publish the `NodeRef` of the children that change.
It also exposes the `Document` to `ContentBuilder` types.
These additions are necessary for efficient updates of child elements in the RealityKit addon library.

Expose the `document` and updated `NodeRef` for addon libraries

---

Sources/BuiltinRegistryGenerator/BuiltinRegistryGenerator.swift

Some minor restructuring to support building with Swift 6 in Xcode 16.
1. Swift 6 struggles to evaluate the availability regex in the BuiltinRegistryGenerator. It has been split into simpler regex pieces.

Xcode 16 beta compatibility

---

Sources/LiveViewNative/Protocols/ContentBuilder.swift

If a `ContentBuilder` uses the default `EmptyContentModifier` type, then it doesn't provide any modifiers that need to be parsed.
In this case, we can skip parsing the stylesheet for the additional modifiers to improve performance.

Skip stylesheet parsing if `ContentBuilder` doesn't provide any modifiers

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift

Closes #1379 
The params sent to the server now look like this:
```ex
%{
"_format" => "swiftui",
"_interface" => %{
"app_build" => "1",
"app_version" => "1.0",
"bundle_id" => "com.example.app",
"internationalization" => %{
"time_zone" => "America/New_York"
},
"localization" => %{
"locale" => "en_US"
},
"os" => "iOS",
"os_version" => "18.0",
"target" => "ios"
}
}
```
Note the addition of the `internationalization` and `localization` keys.

Add nested keys to `_interface` for l10n and i18n

---

Sources/LiveViewNative/ViewModel.swift
Tests/LiveViewNativeTests/FormModelTests.swift

Ran into the same issue as https://github.com/liveview-native/liveview-native-live-form/issues/16 so thought i'd take a shot at fixing it.
Unit testing was not as simple as I'd hoped, and I ran into issues with Views being required to use environment values. Hence only one of the paths is tested.
```bash
Swift:
[debug] HANDLE EVENT "validate" in SaturnWeb.Idine.CheckoutLive
Parameters: %{"_target" => ["payment", "add_loyalty_card"], "payment" => %{"add_loyalty_card" => "true", "payment_type" => "2"}}
[debug] Replied in 400µs
Web:
[debug] HANDLE EVENT "validate" in SaturnWeb.Idine.CheckoutLive
Parameters: %{"_csrf_token" => "DAdXDCskLwJnfCU_BiQLLAIxJTAkDUEMcn1jMnWG09MqqaCi0rUWWzqK", "_target" => ["payment", "add_loyalty_card"], "payment" => %{"add_loyalty_card" => "true", "payment_type" => …
```

fix: phx-change on form sends all form data

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Live/LiveElement.swift
Sources/LiveViewNative/ViewTree.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/List.swift
Sources/LiveViewNative/Views/Layout Containers/Collection Containers/Section.swift

This enables scroll restoration for `List`.
Restoration happens automatically when the `List` element has an `id` attribute.
```html
<List id="my-list">
...
</List>
```
https://github.com/user-attachments/assets/fb3c0d96-3d8b-49aa-84bb-48db12fa55fc

`List` scroll restoration

---

Sources/LiveViewNative/Stylesheets/ViewReference.swift
Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/ModifierGenerator/FunctionParameterSyntax+isViewBuilder.swift
Sources/ModifierGenerator/Signature.swift

Closes #1380 
The `_observeTextReference` modifier tracks changed to the element associated with a `TextReference` type. In the `content` block, modifiers that use the referenced `Text` element can be applied. They will now properly update their contents in response to changes from the server.
In this example, the `navigationTitle` and `badge` modifiers use `TextReference` types, and update when the `count` changes.
```heex
<List style="navigationTitle(:title)">
<Button phx-click="increment" style='badge(:badge)'>
Increment
<Text template="badge">
<%= @count %>
</Text>
</Button>
<Text template="title">
<%= @count %>
</Text>
</List>
```
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/73c87981-7507-42a7-921c-dfccf44e8054

Add `_observeTextReference` to update modifiers with `TextReference` types

---

Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/Environment.swift

When using `pushEvent`, if the server sends `{:reply, %{ ... }, socket}`, the client will now be able to handle the reply.
```swift
let reply: [String:Any]? = try await coordinator.pushEvent(type: "click", event: "my-event", value: SomePayload())
```

Receive reply from `pushEvent`

---

Package.resolved
Package.swift

Use new `swiftlang` org, and resolve package updates

---

priv/templates/lvn.swiftui.gen/core_components.ex

This updates the `flash` component to send the `lv:clear-flash` in response to the button click, instead of the alert dismissal. The dismissal event is sent on iOS, but not macOS. This new solution will work on all platforms.
It should also send the `key`, which the `phx-change` approach likely missed.

Update flash component to dismiss properly on macOS

---

.github/workflows/ci.yml
Sources/LiveViewNative/Coordinators/LiveNavigationEntry.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift

This makes the `LiveSessionCoordinator.navigationPath` public for read-only access.
With this addition, you can now check what URL is currently being displayed, and access the `LiveViewCoordinator` for that navigation path.
In the future, this API could be expanded to allow writing for more advanced client-side navigation.

Expose `navigationPath`

---

Sources/LiveViewNative/Property Wrappers/Event.swift
Sources/LiveViewNative/Property Wrappers/LiveContext.swift
Sources/LiveViewNative/Protocols/ContentBuilder.swift
Sources/LiveViewNative/ViewTree.swift

This fixes instances in addon libraries where a blank (unusable) `LiveContext<R>()` had to be passed to resolve a stylesheet value.
https://github.com/liveview-native/liveview-native-swiftui-charts/blob/c612c5ac085fc61a33a4c3d097d09b0db9a2be7f/Sources/LiveViewNativeCharts/Modifiers/SymbolModifier.swift#L44
Instead, a valid `LiveContext` can be accessed from the `ContentBuilder` context, via `context.context`.
Addon libraries will need to be updated to make use of this new API.

Add access to `LiveContext` from `ContentBuilder`

---

CHANGELOG.md
Sources/LiveViewNative/Stylesheets/Stylesheet.swift
Sources/LiveViewNative/_GeneratedModifiers.swift

The modifiers have been regenerated using Xcode 15.4.
Xcode 15.4 removed `xrOS` references from the `swiftinterface` file for SwiftUI, which fixes an issue with visionOS modifier compilation.
I've also made the `Stylesheet` type to fix a release mode linker error in RC 4.

Update generated modifiers for Xcode 15.4

---

livebooks/markdown/swiftui-views.md
livebooks/swiftui-views.livemd

Fix description for `VStack` where
horizontally was used instead of vertically
Fixes issue #1427

Fix description for VStack

---

CHANGELOG.md
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/Property Wrappers/ChangeTracked.swift

This removes the `collect(.byTime(...))` call in `ChangeTracked`. I'm not sure why we were collecting the values here:
1. Most elements will only send one change per RunLoop iteration
2. Updating the localValue on the next RunLoop can cause animation hitches as seen in the `alert` modifier on macOS.
I believe this was leftover from `native_bindings`, which would collect all updates during a RunLoop and batch them together.

Remove change collection for `ChangeTracked`

---

CHANGELOG.md
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift

`LiveViewCoordinator` is initialised from `LiveSessionCoordinator`, which gets passed in as a parameter to `init` and then retained by the view coordinator. This causes a retain cycle.
Additionally, this is also retained by the `handleEvent` as `session` was used directly in the closure, which then retained it.
This commit fixes both by using a weak reference from the view coordinator to the session coordinator, and accessing the session via the weak `self` reference.

Fix retain cycle in LiveViewCoordinator

---

CHANGELOG.md
Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift

These are passed on to Phoenix when the LiveView makes the initial connection. 
Sample use case: Passing an "Authorization" HTTP header to authenticate a user in the LiveView with a token that's fetched outside of LiveView and stored in the user's keychain. That particular header should not be set on [`URLSessionConfiguration`](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1411532-httpadditionalheaders) directly.
[Related Slack thread](https://elixir-lang.slack.com/archives/C041F3EQHFS/p1726716326675869) for reference.

Allow to set optional headers

---

CHANGELOG.md
Sources/LiveViewNative/Property Wrappers/FormState.swift

Closes #1438 
Previously, `FormState` would use the client-provided fallback value instead of the value in the document when not bound to a `LiveForm`.
Now, any values passed in the template will be used. `Toggle` will reflect the `isOn` attribute, `TextField` will show the provided `text` content, etc. Any fields not bound to a form with a default value cannot be updated. They will revert back to the state provided by the template if modified.
https://github.com/user-attachments/assets/3e1dc603-35ac-40af-b227-c097d471054f

Use value from document as default for unbound `FormState`

---

Sources/LiveViewNative/Stylesheets/ParseableTypes/Styles/AnyDisclosureGroupStyle+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/Styles/AnyNavigationViewStyle+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/Styles/AnyTabViewStyle+ParseableModifierValue.swift
Sources/LiveViewNative/Stylesheets/ParseableTypes/UITextAutocapitalizationType+ParseableModifierValue.swift
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/TabView.swift
Sources/LiveViewNative/_GeneratedModifiers.swift
Sources/ModifierGenerator/FunctionParameterSyntax+isViewBuilder.swift
Sources/ModifierGenerator/ModifierGenerator.swift
Sources/ModifierGenerator/Visitors/ModifierVisitor.swift

This adds the new `sidebarAdaptable` TabViewStyle, and support for the `TabContentBuilder`.
```heex
<TabView phx-change="tab-changed" style="tabViewStyle(.sidebarAdaptable)">
<VStack tag="/" style='tabItem(:item)'>
<Label template="item" systemImage="1.circle">Tab 1</Label>
Tab Content 1
</VStack>
<VStack tag="/detail/red" style='tabItem(:item)'>
<Label template="item" systemImage="2.circle">Tab 2</Label>
Tab Content 2
</VStack>
</TabView>
```

Add new `Tab` elements and `.sidebarAdaptable` TabViewStyle

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Views/Layout Containers/Scroll Views/ScrollView.swift

Scroll restoration is now automatically provided for all `ScrollView` elements with an explicit `id` attribute.
```html
<ScrollView id="cookbook">
...
</ScrollView>
```
Scroll restoration only occurs on back navigation. It is also only available for the `ScrollView` element (not `List` or other scrolling containers)
> [!NOTE]
> Scroll restoration is only available for iOS 18 or later.
https://github.com/user-attachments/assets/dce871ae-d628-4145-9ab3-492971a087ae

Automatic scroll restoration for `ScrollView`

---

CHANGELOG.md
Sources/LiveViewNative/Views/Layout Containers/Presentation Containers/NavigationLink.swift

The `data-phx-link` attribute can be used to set the link to `redirect` or `patch` mode.

Add `patch` support

---

priv/templates/lvn.swiftui.gen/core_components.ex
test/live_view_native/swiftui/core_components_test.exs

This PR adds a `:section` slot to `simple_form/1`. The slot can receive the following optional attributes:
- ~`is_expanded`, boolean. Will be set as `isExpanded` in the sections. Defaults to true.~
- `header`, string. Will add a `<Text template={:header}></Text>` with the same content to the `Section`.
- `footer`, string. Same as header, but with template `footer`.
Also renders conditionally the `Section` containing the actions.
One final caveat is that if any `:section` slot is present, then `@inner_block` is not rendered. This prevents undefined behaviour or expectations to arise.
1. ~Should `is_expanded` be `isExpanded` to be closer to SwiftUI or keep it closer to Elixir?~
2. I could not figure out how to read the SwiftUI documentation so I'm not sure if I'm missing something.

Add `:section` slot to `simple_form`.

---

Package.resolved
Package.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Live/ReconnectLiveViewAction.swift

We need the ability to add additional headers in `connect`, `reconnect`. phoenix will throw a csrf error on live form submission unless `content-type` is set to `application/x-www-form-urlencoded`.  This can already be done by changing the configured headers on the coordinator, but this is more explicit and avoid bugs where setting and unsetting them globally leaves them in the wrong state after a failed connection.

rc-4 changes: Add additional headers to connect, reconnect endpoints on coordinator

---

Sources/LiveViewNative/Views/Layout Containers/Stacks/VStack.swift

Addresses #1507 
There is more discussion likely needed as to whether or not pushing a `.` at the start of `.leading` is necessary or not, but as this convention only appears in styles consistently, the near term solution could just be improving the docs with a simple example. This PR adds such an example to the `VStack` default example.

Adds VStack Alignment Example #1507

---

lib/live_view_native/swiftui/rules_parser/modifiers.ex
lib/live_view_native/swiftui/rules_parser/post_processors.ex
test/live_view_native/swiftui/rules_parser_test.exs

Per-Carson's request the representation of member expressions is going to change to make the SwiftUI parsing easier to reason about
@NduatiK I've made a few updates to the tsets but after those tests are green I suspect other tests will fail as the new format hasn't been update everywhere in the test suite,
More details on the syntax
I seem to recall that @NduatiK or @carson-katri recommended this format last year.

New member expression syntax

---

CHANGELOG.md
lib/live_view_native/swiftui/rules_parser/modifiers.ex
lib/live_view_native/swiftui/rules_parser/tokens.ex
test/live_view_native/swiftui/rules_parser_test.exs

This should make porting rules from SwiftUI examples easier
Now all of these formats are accepted:
```
foo()
.foo()
foo();
.foo();
```
This is to solve two annoyances:
1. copying modifiers from SwiftUI examples has leading `.` on each modifier. Now you can just drop these in.
2. People familiar with CSS have been adding `;` at the end of each line. This was re-inforced when we support `;` separator in the `style` attr in-template.

Ignore leading dots and trailing semicolons

---

Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift

because the channel never is upgraded to a strong reference it is retained after close, you can confirm this in the xcode memory graph view.

retain cycle fix

---

Package.swift
Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Sources/LiveViewNative/Live/LiveView.swift
Sources/LiveViewNative/NavStackEntryView.swift

Additionally: cleanup memory leaks which leak web socket connections. This means we will postpone moving to the LiveViewClient API until 0.4.1

Upgrade core to 0.4.1-rc1

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift

It seems that `assets_change` events cancel the parent event during reconnect causing the connect to be aborted.

don't cancel running reconnect

---

Sources/LiveViewNative/Stylesheets/ResolvableTypes/SwiftUI/Styles/ListStyle.swift

The macro conditionals aren't quite right for `insetgrouped` causing a compilation error on desktop MacOs

Prevent nonexistant variant from breaking MacOs Desktop Builds

---

CHANGELOG.md
Sources/LiveViewNative/ViewModel.swift

The `FileUpload` type and `LiveViewModel.fileUpload(id:)` allow you to create custom previews for selected files, similar to the `<.live_img_preview>` component.
For example, here is a custom View that generates a thumbnail preview for a selected video file.
It can be used in place of `live_img_preview`:
```heex
<LiveVideoPreview data-phx-upload-ref={entry.upload_ref} />
```
```swift
import AVKit
@LiveElement
struct LiveVideoPreview<Root: RootRegistry>: View {
@LiveAttribute("data-phx-upload-ref")
private var phxUploadRef: String?
@LiveElementIgnored
@EnvironmentObject
private var liveViewModel: LiveViewModel
@LiveElementIgnored
@State
private var thumbnail: Image?
var body: some View {
if let phxUploadRef,
let upload = liveViewModel.fileUpload(id: phxUploadRef)
{
VStack {
if let …
```

Expose FileUpload types and API

---

Sources/ASTDecodableImplementation/Decoders/InitializerClausesDecoder.swift
Sources/LiveViewNative/LiveViewNative.docc/AddCustomModifier.md
Sources/LiveViewNative/Protocols/ContentBuilder.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/Accessibility.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/AppKit.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/CoreGraphics.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/CoreText.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/DeveloperToolsSupport.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/Foundation.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/QuartzCore.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/Spatial.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/StandardLibrary.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/SwiftUI/Anchor.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/SwiftUI/EdgeSet.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/SwiftUI/NamedCoordinateSpace.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/SwiftUI/ScrollTargetBehavior.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/SwiftUI/Styles/IndexViewStyle.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/SwiftUI/Styles/ShapeStyle.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/SwiftUI/Styles/TabViewStyle.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/Symbols.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/UIKit.swift
Sources/LiveViewNative/Stylesheets/ResolvableTypes/WatchKit.swift
Sources/LiveViewNative/Stylesheets/StylesheetResolvable.swift
Sources/ModifierGenerator/StyleDefinitionGenerator/makeResolvableType.swift

The code-generated `Resolvable` subtypes were made public for use in addons.
For example, an addon can now create a modifier that has a `Alignment.Resolvable` argument.
The `StylesheetResolvable` protocol was also made public, and an extension to implement `resolve` that takes a `ContentBuilder.Context` instead of a `LiveContext`.

Expose generated Resolvable types for addons

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift

presently the liveview channel enters a zombie state - claiming to be joined, after it's Genserver counterpart has panicked and exited. this is expected behavior without and error handling clause to reconnect.

reconnect livechannel on error

---

Sources/SwiftSyntaxExtensions/ValueResolution.swift

This resolves an issue with the `tint` modifier, where the Color was not properly applied, and fell back to `Color.red`.
Its possible this also affected other modifiers that had optional type eraser types as arguments.

Properly resolve optional type erasers

---

Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift

Diffs handled internally will throw a thread assertion.

Handle diff on main actor

---

Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift

When connecting from an error view the livereload channel is not properly freed. This ammends that to prevent a resource leak when reconnecting from the error view.

prevent leak when reconnecting from error view
